'use client';

import { useState } from 'react';
import { CheckCircle2, Copy, Download, ExternalLink, Info } from 'lucide-react';
import type { GenerationOutput, SceneScript } from '@/types';
import { CREDIT_COST } from '@/lib/credits';
import { getLang } from './LanguageSwitcher';
import { useLanguage } from './LanguageProvider';

const TABS = ['overview', 'structure', 'scenes', 'prompts', 'voice', 'timeline'] as const;
type Tab = typeof TABS[number];
type PromptKey = keyof SceneScript['ai_prompts'];
const UI = {
  ko: { tabs: ['한눈에 보기', '바이럴 구조', '장면별 제작 플랜', 'AI 영상 프롬프트', '음성·자막', '편집 타임라인'], guides: ['완성된 영상의 핵심 내용을 요약해서 보는 곳입니다. 제목, 콘셉트, 후킹 문구와 마지막 행동 유도 문구를 먼저 확인하세요.', '참고 영상에서 복사하지 않고 추출한 시청자 관심 유도 방식입니다. 다른 주제에도 적용할 수 있는 흐름을 보여줍니다.', '각 장면에서 무엇을 촬영하거나 생성해야 하는지 설명합니다. 화면, 행동, 카메라, 조명과 소리를 확인하세요.', 'Veo, Runway, Kling 같은 AI 영상 도구에 장면별로 넣을 영어 지시문입니다. 원하는 도구의 프롬프트를 복사해 사용하세요.', '장면마다 사용할 내레이션과 화면 자막입니다. 한국어·영어·일본어 버전을 비교하고 선택할 수 있습니다.', '영상의 시간 순서에 맞춰 장면, 자막, 내레이션, 효과음과 전환을 배치한 편집용 가이드입니다.'], overview: '이 화면은 완성된 영상 설계안을 빠르게 검토하는 요약본입니다. 아래 탭에서 장면, 프롬프트, 대본과 편집 순서를 자세히 볼 수 있습니다.', copy: '복사', copied: '복사됨', failed: '복사 실패', scenePrompt: '장면별 프롬프트 복사', promptCopy: '프롬프트 복사', allPrompt: '전체 프롬프트 복사', allResult: '전체 결과 복사', json: 'JSON 다운로드', txt: 'TXT 다운로드', original: '원본 영상 보기', fields: ['화면', '등장인물·대상', '행동', '핵심 대상 노출', '카메라 샷', '카메라 움직임', '렌즈', '조명', '색감', '감정', '내레이션', '자막', '효과음', 'BGM'], narration: '내레이션', caption: '자막', effects: '효과음', music: 'BGM', emotion: '감정 톤', scene: '장면', purpose: '원본 고유 표현을 제외하고 재사용 가능한 구조만 추상화했습니다.', restricted: '복제 금지 요소', visual: '영상', transition: '전환', note: '메모' },
  en: { tabs: ['Overview', 'Viral Structure', 'Scene Plan', 'AI Prompts', 'Voice & Captions', 'Editing Timeline'], guides: ['A quick summary of the finished video plan. Start with the title, concept, hook, and call to action.', 'Reusable viewer-engagement mechanics abstracted from the reference without copying its wording or scenes.', 'Instructions for what to film or generate in each scene, including action, camera, lighting, and sound.', 'English instructions to paste into tools such as Veo, Runway, or Kling. Copy the prompt for your chosen tool.', 'Narration and on-screen captions for each scene in Korean, English, and Japanese.', 'A time-ordered editing guide for scenes, captions, narration, sound effects, and transitions.'], overview: 'Use this page to review the finished video plan at a glance. Open the tabs below for production details.', copy: 'Copy', copied: 'Copied', failed: 'Copy failed', scenePrompt: 'Copy scene prompt', promptCopy: 'Copy prompt', allPrompt: 'Copy all prompts', allResult: 'Copy full result', json: 'Download JSON', txt: 'Download TXT', original: 'View source video', fields: ['Visual', 'Subject', 'Action', 'Product placement', 'Camera shot', 'Camera movement', 'Lens', 'Lighting', 'Color', 'Emotion', 'Narration', 'Caption', 'Sound effect', 'BGM'], narration: 'Narration', caption: 'Caption', effects: 'Sound effect', music: 'BGM', emotion: 'Tone', scene: 'Scene', purpose: 'Reusable structure abstracted without copying source-specific expression.', restricted: 'Do not copy', visual: 'Video', transition: 'Transition', note: 'Note' },
  zh: { tabs: ['概览', '爆款结构', '分镜方案', 'AI 视频提示词', '语音与字幕', '剪辑时间线'], guides: ['快速查看完整视频方案的核心内容。先确认标题、概念、开场和行动号召。', '从参考视频中提取的可复用吸引力结构，不复制原文或原画面。', '说明每个场景要拍摄或生成的画面、动作、镜头、灯光和声音。', '可复制到 Veo、Runway、Kling 等工具中的英文指令。', '每个场景的旁白和屏幕字幕，支持韩语、英语和日语。', '按时间排列的画面、字幕、旁白、音效和转场编辑指南。'], overview: '这里是完整视频方案的快速摘要。点击下方标签查看详细制作内容。', copy: '复制', copied: '已复制', failed: '复制失败', scenePrompt: '复制场景提示词', promptCopy: '复制提示词', allPrompt: '复制全部提示词', allResult: '复制完整结果', json: '下载 JSON', txt: '下载 TXT', original: '查看原视频', fields: ['画面', '主体', '动作', '产品展示', '镜头', '镜头运动', '镜头焦段', '灯光', '色彩', '情绪', '旁白', '字幕', '音效', '背景音乐'], narration: '旁白', caption: '字幕', effects: '音效', music: '背景音乐', emotion: '情绪', scene: '场景', purpose: '抽象出可复用的结构，不复制原视频的表达。', restricted: '禁止复制', visual: '画面', transition: '转场', note: '备注' },
  ja: { tabs: ['概要', 'バイラル構成', 'シーン構成', 'AIプロンプト', '音声・字幕', '編集タイムライン'], guides: ['完成した動画プランの要点を確認する画面です。タイトル、コンセプト、フック、CTAを確認します。', '参考動画から抽象化した再利用可能な構成です。元の表現や映像はコピーしません。', '各シーンで撮影・生成する内容、動き、カメラ、照明、音を説明します。', 'Veo、Runway、Klingなどに貼り付ける英語の指示文です。', '各シーンのナレーションと画面字幕を韓国語・英語・日本語で確認できます。', '映像、字幕、ナレーション、効果音、トランジションの編集順を示します。'], overview: '完成した動画プランの概要です。下のタブから詳しい制作内容を確認できます。', copy: 'コピー', copied: 'コピー済み', failed: 'コピー失敗', scenePrompt: 'シーンプロンプトをコピー', promptCopy: 'プロンプトをコピー', allPrompt: '全プロンプトをコピー', allResult: '全結果をコピー', json: 'JSONをダウンロード', txt: 'TXTをダウンロード', original: '元動画を見る', fields: ['映像', '対象', '動作', '商品配置', 'カメラショット', 'カメラ動作', 'レンズ', '照明', '色味', '感情', 'ナレーション', '字幕', '効果音', 'BGM'], narration: 'ナレーション', caption: '字幕', effects: '効果音', music: 'BGM', emotion: '感情トーン', scene: 'シーン', purpose: '元動画の固有表現をコピーせず、再利用できる構成だけを抽象化しました。', restricted: 'コピー禁止要素', visual: '映像', transition: 'トランジション', note: 'メモ' },
};

type ResultUi = typeof UI.ko;

function CopyButton({ text, label, ui }: { text: string; label: string; ui: ResultUi }) {
  const [copied, setCopied] = useState(false);
  const [failed, setFailed] = useState(false);
  return <button type="button" onClick={async () => { try { await navigator.clipboard.writeText(text); setCopied(true); setFailed(false); window.setTimeout(() => setCopied(false), 1500); } catch { setFailed(true); } }} className="inline-flex items-center gap-1.5 rounded-lg border border-violet-400/25 bg-violet-400/10 px-3 py-2 text-xs font-semibold text-violet-200 hover:bg-violet-400/20">{copied ? <CheckCircle2 size={12} /> : <Copy size={12} />}{failed ? ui.failed : copied ? ui.copied : label}</button>;
}

function download(name: string, content: string, type: string) {
  const url = URL.createObjectURL(new Blob([content], { type }));
  const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url);
}

function ScenePlan({ scene, ui }: { scene: SceneScript; ui: ResultUi }) {
  const details = ui.fields.map((label, index) => [label, [scene.visual_description, scene.subject_description, scene.subject_action, scene.product_placement, scene.camera_shot, scene.camera_movement, scene.lens, scene.lighting, scene.color_mood, scene.emotion, scene.audio_script.kr, scene.captions.kr, scene.sound_effect, scene.background_music][index]]);
  return <article className="rounded-2xl border border-white/8 bg-white/[0.025] p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm font-bold text-white">{ui.scene} {scene.scene_number} — {scene.purpose}</p><p className="mt-1 text-xs text-cyan-300">{scene.start_time}~{scene.end_time}</p></div><CopyButton text={scene.ai_prompts.generic} label={ui.scenePrompt} ui={ui} /></div><div className="grid gap-3 sm:grid-cols-2">{details.map(([label, value]) => <div key={label} className="rounded-xl bg-black/15 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-white/35">{label}</p><p className="mt-1 text-xs leading-relaxed text-white/70">{value}</p></div>)}</div></article>;
}

export default function GenerationResult({ result, creditsRemaining, creditCostApplied = CREDIT_COST.FULL_ANALYSIS, showCreditSummary = true }: { result: GenerationOutput; creditsRemaining?: number; creditCostApplied?: number; showCreditSummary?: boolean }) {
  useLanguage();
  const [tab, setTab] = useState<Tab>('overview');
  const [guideTab, setGuideTab] = useState<Tab | null>(null);
  const language = getLang();
  const ui = UI[language] ?? UI.ko;
  const json = JSON.stringify(result, null, 2);
  const creditSummary = {
    ko: ['크레딧', `${creditCostApplied}크레딧 소모 · 현재 잔여 ${creditsRemaining ?? '—'}크레딧`],
    en: ['Credits', `${creditCostApplied} credits used · ${creditsRemaining ?? '—'} credits remaining`],
    zh: ['积分', `消耗 ${creditCostApplied} 积分 · 剩余 ${creditsRemaining ?? '—'} 积分`],
    ja: ['クレジット', `${creditCostApplied}クレジット消費 · 残り ${creditsRemaining ?? '—'}クレジット`],
  }[language];
  const allPrompts = result.scenes.map((scene) => `Scene ${scene.scene_number}\nVeo:\n${scene.ai_prompts.veo}\n\nRunway:\n${scene.ai_prompts.runway}\n\nKling:\n${scene.ai_prompts.kling}\n\nGeneric:\n${scene.ai_prompts.generic}`).join('\n\n---\n\n');
  const overview = [
    [language === 'ko' ? '프로젝트 제목' : language === 'ja' ? 'プロジェクトタイトル' : language === 'zh' ? '项目标题' : 'Project title', result.project_title],
    [language === 'ko' ? '새 영상 콘셉트' : language === 'ja' ? '新しい動画コンセプト' : language === 'zh' ? '新视频概念' : 'New video concept', result.concept],
    [language === 'ko' ? '콘텐츠 목적' : language === 'ja' ? 'コンテンツの目的' : language === 'zh' ? '内容目标' : 'Content goal', result.video_goal],
    [language === 'ko' ? '예상 영상 길이' : language === 'ja' ? '動画の長さ' : language === 'zh' ? '预计视频时长' : 'Estimated duration', `${result.duration_seconds}${language === 'ko' ? '초' : 's'}`],
    [language === 'ko' ? '핵심 후킹 문구' : language === 'ja' ? 'フック' : language === 'zh' ? '核心钩子' : 'Core hook', result.hook],
    [language === 'ko' ? '마무리 문구' : language === 'ja' ? '締めの文句' : language === 'zh' ? '结尾文案' : 'Closing line', result.final_cta],
    [language === 'ko' ? '바이럴 전략' : language === 'ja' ? 'バイラル戦略' : language === 'zh' ? '爆款策略' : 'Viral strategy', result.overall_viral_strategy],
    ...(showCreditSummary ? [creditSummary] : []),
  ];
  const structure = Object.entries(result.structure_analysis).filter(([key]) => key !== 'restricted_elements');

  return <section className="space-y-4 fade-in-up"><div role="tablist" aria-label={ui.overview} className="flex gap-2 overflow-x-auto rounded-2xl border border-white/8 bg-[#0d0d14]/90 p-2">{TABS.map((item, index) => <div key={item} className="relative shrink-0"><button role="tab" aria-selected={tab === item} onClick={() => { setTab(item); setGuideTab(null); }} className={`rounded-xl px-3 py-2 pr-8 text-xs font-semibold transition-all ${tab === item ? 'bg-violet-600 text-white' : 'text-white/45 hover:bg-white/5 hover:text-white'}`}>{ui.tabs[index]}</button><button type="button" aria-label={`${ui.tabs[index]} info`} onClick={() => setGuideTab(guideTab === item ? null : item)} className="absolute right-2 top-1/2 flex h-4 w-4 -translate-y-1/2 items-center justify-center rounded-full border border-cyan-300/50 text-[10px] font-black text-cyan-200 hover:bg-cyan-400/20"><Info size={10} /></button>{guideTab === item && <div className="absolute left-0 top-full z-20 mt-2 w-64 rounded-xl border border-cyan-300/25 bg-[#11121c] p-3 text-left text-[11px] leading-relaxed text-white/75 shadow-xl">{ui.guides[index]}</div>}</div>)}</div>
    <div className="rounded-2xl border border-white/8 bg-[#0d0d14]/80 p-5 sm:p-6">
      {tab === 'overview' && <div className="space-y-4"><p className="rounded-xl border border-cyan-400/15 bg-cyan-400/5 p-3 text-xs leading-relaxed text-cyan-100/75">{ui.overview}</p><div className="grid gap-3 sm:grid-cols-2">{overview.map(([label, value]) => <div key={label} className="rounded-xl border border-white/6 bg-white/[0.025] p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-violet-300">{label}</p><p className="mt-2 text-sm leading-relaxed text-white/75">{value}</p></div>)}</div></div>}
      {tab === 'structure' && <div className="space-y-4"><p className="text-xs text-cyan-200">{ui.purpose}</p><div className="grid gap-3 sm:grid-cols-2">{structure.map(([key, value]) => <div key={key} className="rounded-xl border border-white/6 p-4"><p className="text-[10px] uppercase text-white/35">{key.replaceAll('_', ' ')}</p><p className="mt-2 text-sm text-white/70">{String(value)}</p></div>)}</div><div className="rounded-xl border border-red-400/15 bg-red-400/5 p-4"><p className="text-xs font-bold text-red-200">{ui.restricted}</p><p className="mt-2 text-xs text-white/55">{result.structure_analysis.restricted_elements.join(' · ')}</p></div></div>}
      {tab === 'scenes' && <div className="space-y-3">{result.scenes.map((scene) => <ScenePlan key={scene.scene_number} scene={scene} ui={ui} />)}</div>}
      {tab === 'prompts' && <div className="space-y-4"><div className="flex flex-wrap gap-2">{([['veo', 'Veo'], ['runway', 'Runway'], ['kling', 'Kling'], ['generic', 'Generic']] as [PromptKey, string][]).map(([key, label]) => <CopyButton key={key} label={`${label} ${ui.promptCopy}`} ui={ui} text={result.scenes.map((scene) => scene.ai_prompts[key]).join('\n\n')} />)}<CopyButton label={ui.allPrompt} ui={ui} text={allPrompts} /></div>{result.scenes.map((scene) => <article key={scene.scene_number} className="rounded-xl border border-white/8 p-4"><p className="mb-3 text-xs font-bold text-white">{ui.scene} {scene.scene_number}</p>{(['veo', 'runway', 'kling', 'generic'] as PromptKey[]).map((key) => <div key={key} className="mb-3"><p className="text-[10px] font-bold uppercase text-violet-300">{key}</p><p className="mt-1 whitespace-pre-wrap text-xs leading-relaxed text-white/55">{scene.ai_prompts[key]}</p></div>)}</article>)}</div>}
      {tab === 'voice' && <div className="space-y-4">{result.scenes.map((scene) => <article key={scene.scene_number} className="rounded-xl border border-white/8 p-4"><p className="text-xs font-bold text-white">{ui.scene} {scene.scene_number} · {scene.start_time}~{scene.end_time}</p>{(['kr', 'us', 'jp'] as const).map((language) => <div key={language} className="mt-3 grid gap-2 sm:grid-cols-2"><p className="text-xs text-white/60"><b className="text-cyan-300">{language.toUpperCase()} {ui.narration}</b><br />{scene.audio_script[language]}</p><p className="text-xs text-white/60"><b className="text-violet-300">{language.toUpperCase()} {ui.caption}</b><br />{scene.captions[language]}</p></div>)}<p className="mt-3 text-xs text-white/45">{ui.effects}: {scene.sound_effect} · {ui.music}: {scene.background_music} · {ui.emotion}: {scene.emotion}</p></article>)}</div>}
      {tab === 'timeline' && <div className="space-y-3">{result.editing_timeline.map((item, index) => <article key={`${item.start_time}-${index}`} className="grid gap-2 rounded-xl border border-white/8 p-4 text-xs text-white/60 sm:grid-cols-[100px_1fr]"><b className="text-cyan-300">{item.start_time}~{item.end_time}</b><div><p>{ui.visual}: {item.visual}</p><p>{ui.caption}: {item.caption}</p><p>{ui.narration}: {item.voiceover}</p><p>{ui.effects}: {item.sound_effect}</p><p>{ui.music}: {item.background_music}</p><p>{ui.transition}: {item.transition}</p><p>{ui.note}: {item.editing_note}</p></div></article>)}</div>}
    </div>
    <div className="flex flex-wrap gap-2"><CopyButton text={json} label={ui.allResult} ui={ui} /><button onClick={() => download('video-production-plan.json', json, 'application/json')} className="inline-flex items-center gap-1.5 rounded-lg border border-cyan-400/25 bg-cyan-400/10 px-3 py-2 text-xs font-semibold text-cyan-200"><Download size={12} />{ui.json}</button><button onClick={() => download('video-production-plan.txt', allPrompts, 'text/plain')} className="inline-flex items-center gap-1.5 rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs text-white/60"><Download size={12} />{ui.txt}</button>{result.source_url && <a href={result.source_url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs text-white/60"><ExternalLink size={12} />{ui.original}</a>}</div>
  </section>;
}
