'use client';

import { useState, useEffect } from 'react';
import { Globe } from 'lucide-react';

type Lang = 'ko' | 'en' | 'zh' | 'ja';

const LANGS: { code: Lang; label: string; flag: string }[] = [
  { code: 'ko', label: '한국어', flag: '🇰🇷' },
  { code: 'en', label: 'English', flag: '🇺🇸' },
  { code: 'zh', label: '中文', flag: '🇨🇳' },
  { code: 'ja', label: '日本語', flag: '🇯🇵' },
];

// 간단한 번역 테이블
export const T: Record<Lang, Record<string, string>> = {
  ko: {
    // ─── Navbar ───
    nav_generator: '대본 생성',
    nav_credits: '크레딧',
    nav_trends: '최신 트렌드',
    nav_invite: '초대하기',
    nav_login: '로그인',
    nav_signup: '회원가입',
    nav_start_free: '무료로 시작하기',
    nav_my_account: '내 계정',
    nav_logged_in_as: '로그인된 계정',
    nav_history: '생성 히스토리',
    nav_charge: '크레딧 충전',
    nav_settings: '계정 설정',
    nav_logout: '로그아웃',
    nav_mobile_invite: '👥 친구 초대하기',
    nav_features: '기능 소개',
    announcement_bonus: '🎉 신규 가입 시 크레딧 10개 무료 지급 ·',
    announcement_signup: '지금 가입하기',
    credits_label: '크레딧',

    // ─── Hero ───
    hero_tag: 'AI 기반 숏폼 마케팅 분석',
    hero_title: '숏폼 URL 하나로',
    hero_title2: '3개국 바이럴 대본 생성',
    hero_desc: 'AI가 영상 구조를 분석하고 귀사의 상품에 맞춘 한국·미국·일본 현지화 대본을 1분 만에 완성합니다.',
    cta_start: '지금 무료로 시작',
    cta_credits: '크레딧 보기',

    // ─── Stats ───
    stats_gen_value: '약 2분',
    stats_gen: '평균 생성 시간',
    stats_locale_value: '3개국',
    stats_locale: '동시 현지화',
    stats_uptime_value: '베타',
    stats_uptime: '서비스 상태',
    stats_scripts_value: '100+',
    stats_scripts: '생성된 대본',

    // ─── Features ───
    features_title: '왜 ViralScript AI인가요?',
    features_desc: '단순한 번역이 아닙니다. 각국의 트렌드와 감성을 이해한 AI가 진짜 바이럴을 만듭니다.',
    feature_viral_title: '바이럴 구조 분석',
    feature_viral_desc: 'AI가 숏폼 영상의 후킹 패턴, 감정 곡선, 전환 구조를 초 단위로 분석합니다.',
    feature_localize_title: '3개국 동시 로컬라이징',
    feature_localize_desc: '한국·미국·일본의 문화적 맥락과 인터넷 밈을 반영한 현지화 대본을 즉시 생성합니다.',
    feature_visual_title: 'AI 비주얼 콘티',
    feature_visual_desc: 'Runway, Midjourney용 영상 프롬프트를 씬별로 자동 생성합니다.',
    feature_cache_title: '캐시 적중 시 70% 절감',
    feature_cache_desc: '동일 URL 재분석 시 크레딧 3개 → 1개. 팀 협업에 최적화된 스마트 캐싱.',

    // ─── Pricing / Free Credits ───
    pricing_title: '무료로 시작하세요',
    pricing_desc: '광고 시청 · 출석 룰렛 · 친구 초대로 무료 크레딧을 충전하세요',
    free_roulette_title: '출석 룰렛',
    free_roulette_desc: '매일 접속하고 룰렛을 돌려 최대 10 크레딧 획득',
    free_roulette_badge: '매일 무료',
    free_ad_title: '광고 보상 충전',
    free_ad_desc: '30초 광고를 보고 즉시 3 크레딧 무료 충전 (하루 최대 5회)',
    free_ad_badge: '하루 5회',
    free_invite_title: '친구 초대',
    free_invite_desc: '친구가 가입하면 나도 3 크레딧, 친구도 3 크레딧',
    free_invite_badge: '무제한',
    recommended: '추천',

    // ─── Footer ───
    footer_disclaimer: '본 플랫폼은 사용자가 제출한 URL의 원본을 저장·전송·재배포하지 않으며, AI 결과물은 마케팅 분석을 위한 2차 창작 가이드입니다.',
    footer_terms: '이용약관',
    footer_privacy: '개인정보처리방침',

    // ─── Auth Modal ───
    auth_welcome_back: '다시 오신 걸 환영해요',
    auth_nice_to_meet: '만나서 반가워요! 🎉',
    auth_reset_password: '비밀번호 재설정',
    auth_login_desc: '계속하려면 로그인해 주세요',
    auth_signup_desc: '지금 가입하고 크레딧 10개를 바로 받아가세요 ✨',
    auth_forgot_desc: '가입한 이메일 주소를 입력해 주세요',
    auth_name_placeholder: '이름',
    auth_email_placeholder: '이메일 주소',
    auth_password_placeholder: '비밀번호 (특수문자 1개 이상 포함)',
    auth_forgot_password_link: '비밀번호를 잊으셨나요?',
    auth_forgot_email_link: '이메일을 잊으셨나요?',
    auth_login_btn: '로그인',
    auth_signup_btn: '회원가입 하기',
    auth_reset_btn: '재설정 링크 발송',
    auth_no_account: '계정이 없으신가요?',
    auth_has_account: '이미 계정이 있으신가요?',
    auth_back_to_login: '로그인으로 돌아가기',
    auth_free_signup: '회원가입',
    auth_agree_terms: '가입 시 이용약관 및 개인정보처리방침에 동의합니다.',
    auth_password_special_char: '비밀번호는 최소 1개의 특수문자(!@#$%^&*)를 포함해야 합니다.',
    auth_email_not_confirmed: '이메일 인증을 완료해야 로그인할 수 있습니다. 메일함을 확인해 주세요.',
    auth_network_error: '네트워크 오류가 발생했습니다. 다시 시도해 주세요.',
    auth_login_success: '로그인 성공! 잠시 후 이동합니다.',
    auth_signup_success: '가입 완료! 이메일 인증 후 로그인해 주세요. 📧',
    auth_email_sent_title: '인증 이메일 발송 완료',
    auth_email_sent_desc: '인증 이메일이 발송되었습니다. 이메일 수신함(스팸함 포함)에서 인증 링크를 클릭해 가입을 완료해 주세요.',
    auth_email_already_exists: '이미 가입된 이메일 주소입니다.',
    auth_verify_expired: '인증 시간이 만료되었습니다. 회원가입을 처음부터 다시 시도해 주세요.',
    auth_resend_email: '인증 이메일 재발송',
    auth_resend_wait: '1분 후 재발송 가능',
    auth_email_resent: '인증 이메일이 재발송되었습니다.',
    auth_retry_signup: '처음부터 다시 가입하기',
    auth_close: '닫기',

    // ─── Find Email ───
    find_email_title: '이메일 찾기',
    find_email_desc: '가입 시 등록한 이름과 전화번호를 입력하세요.',
    find_email_phone_placeholder: '전화번호 (숫자만 입력)',
    find_email_result_label: '조회된 이메일 계정',
    find_email_search_btn: '이메일 조회하기',
    find_email_not_found: '일치하는 유저 정보를 찾을 수 없습니다.',
    find_email_phone_disclaimer: '* 전화번호는 계정 이메일 찾기 목적으로만 안전하게 사용됩니다.',
    signup_phone_disclaimer: '* 전화번호는 계정 이메일 찾기 목적으로만 안전하게 사용됩니다.',
    terms_label: '이용약관',
    privacy_label: '개인정보처리방침',
    auth_agree_terms_prefix: '가입 시 ',
    auth_agree_terms_suffix: '에 동의합니다.',
    and_label: '및',
    signup_phone_placeholder: '전화번호',

    // ─── OTP Email Verification ───
    otp_title: '이메일 인증',
    otp_desc: '{email}로 6자리 인증번호를 발송했습니다',
    otp_placeholder: '인증번호 6자리',
    otp_verify_btn: '인증 완료',
    otp_resend_btn: '인증번호 재발송',
    otp_resend_cooldown: '{seconds}초 후 재발송 가능',
    otp_expired: '인증번호가 만료되었습니다. 재발송 버튼을 눌러주세요.',
    otp_invalid: '인증번호가 일치하지 않거나 만료되었습니다. 다시 확인해 주세요.',
    otp_sending: '인증번호 발송 중...',
    otp_verified: '인증 완료! 잠시 후 이동합니다.',
    otp_change_email: '이메일 변경',

    // ─── Daily Reward Wheel ───
    daily_bonus: '데일리 보너스',
    daily_roulette_title: '데일리 럭키 룰렛',
    daily_roulette_desc: '매일 로그인하고 무료 크레딧을 받아보세요!',
    daily_spin: '룰렛 돌리기',
    daily_claimed: '오늘 이미 받음',
    daily_result_win: '🎉 {amount} 크레딧 획득!',
    daily_result_lose: '😅 꽝! 내일 다시 도전하세요',
    daily_1_credit: '1 크레딧',
    daily_2_credits: '2 크레딧',
    daily_3_credits: '3 크레딧',
    daily_5_credits: '5 크레딧',
    daily_10_credits: '10 크레딧',
    daily_none: '꽝!',

    // ─── Referral System ───
    referral_title: '친구 초대하고 크레딧 받기',
    referral_desc: '친구를 초대하면 당신과 친구 모두 3 크레딧을 받습니다!',
    referral_invited_friends: '초대한 친구',
    referral_credits_earned: '받은 크레딧',
    referral_max_earn: '최대 적립',
    referral_my_code: '내 추천인 코드',
    referral_copy_link: '초대 링크 복사하기',
    referral_copied: '링크 복사 완료!',
    referral_share: '공유하기',
    referral_kakao: '카카오톡',
    referral_twitter: '트위터',
    referral_how: '작동 방식',
    referral_step1_title: '링크 공유',
    referral_step1_desc: '친구에게 내 추천 링크를 보내세요',
    referral_step2_title: '친구 가입',
    referral_step2_desc: '친구가 내 링크로 가입하면 3 크레딧 즉시 지급',
    referral_step3_title: '나도 3 크레딧 획득',
    referral_step3_desc: '친구가 가입할 때마다 나에게도 3 크레딧이 추가됩니다',

    // ─── Rewarded Ad Popup ───
    ad_watch_title: '광고 보고 크레딧 받기',
    ad_watch_desc: '30초 광고를 시청하고 3 크레딧을 무료로 받으세요!',
    ad_watch_btn: '광고 시청하기',
    ad_watching: '광고 시청 중...',
    ad_skip: '건너뛰기',
    ad_complete: '시청 완료!',
    ad_claim: '크레딧 받기',
    ad_limit_reached: '오늘 광고 시청 한도에 도달했습니다. 내일 다시 시도해 주세요.',
    ad_error: '오류가 발생했습니다',

    // ─── Trend Feed ───
    trend_title: '글로벌 트렌드',
    trend_curating: 'AI 큐레이팅 중...',
    trend_fallback: 'Fallback 모드',
    trend_filter_all: '전체',
    trend_no_data: '아직 트렌드 데이터가 없습니다',
    trend_region_all: '전체 지역',
    trend_region_kr: '한국',
    trend_region_us: '미국',
    trend_region_jp: '일본',
    trend_region_cn: '중국',
    trend_load_more: '더 보기',
    trend_views: '조회수',
    trend_likes: '좋아요',
    trend_visit: '바로가기',

    // ─── Trends Page ───
    trends_page_title: '실시간 글로벌 트렌드',
    trends_page_subtitle: '최신 트렌드',
    trends_page_desc: '각 플랫폼의 인기 숏폼을 확인하고 분석해보세요',

    // ─── Pricing Page ───
    pricing_page_title: '크레딧 충전 플랜',
    pricing_page_desc: '필요할 때만 충전하세요. 구독 없음, 만료 없음.',
    pricing_page_free_title: '무료로 시작하세요',
    pricing_page_free_desc: '광고 시청으로 크레딧을 충전하고 무한 분석을 즐기세요.',
    pricing_most_popular: '가장 인기',
    pricing_charge_btn: '충전하기',
    pricing_secure: '안전한 결제 처리',
    pricing_instant: '즉시 크레딧 지급',
    pricing_refund: '환불 정책 보장',
    pricing_login_prompt: '로그인하고 무료 크레딧을 받아보세요!',
    pricing_login_desc: '광고 시청, 출석 룰렛, 친구 초대로 무료 크레딧을 충전할 수 있습니다.',
    pricing_login_btn: '로그인하고 시작하기',
    pricing_roulette_action: '룰렛 돌리기',
    pricing_ad_action: '광고 보고 충전하기',
    pricing_invite_action: '초대하기',

    // ─── Generator Page ───
    gen_title: 'AI 대본 생성기',
    gen_subtitle: '숏폼 URL을 입력하고 3개국 바이럴 대본을 생성하세요',
    gen_url_placeholder: '숏폼 URL을 입력하세요 (TikTok, YouTube Shorts, Instagram Reels)',
    gen_product_placeholder: '홍보할 제품/서비스명 (선택사항)',
    gen_analyze_btn: '분석 시작',
    gen_analyzing: '분석 중...',
    gen_credits_required: '필요 크레딧',
    gen_no_credits: '크레딧이 부족합니다',
    gen_cached: '⚡ 캐시됨',
    gen_new: '✨ 새로 생성',
    gen_copy: '복사',
    gen_copied: '복사됨',
    gen_remix: '리믹스',
    gen_scenes: 'Scenes',
    gen_scene: 'Scene',
    gen_hook_strategy: 'Hook Strategy',
    gen_script: 'Script',
    gen_ai_prompt: 'AI Video Prompt',
    gen_expand: '더보기',
    gen_collapse: '접기',
    gen_login_required: '서비스 이용 시 로그인이 필요합니다',
    gen_login_desc: '기능을 사용하려면 로그인 또는 회원가입을 해주세요.',
    gen_login_btn: '로그인 하기',
    gen_url_invalid: '유튜브 쇼츠, 틱톡, 인스타 릴스 링크만 분석 가능합니다.',
    gen_url_label: '숏폼 영상 URL',
    gen_product_label: '홍보할 상품 / 서비스명',
    gen_custom_prompt_label: '추가 요청사항',
    gen_optional: '선택',
    gen_custom_prompt_placeholder: '예: 20대 여성 타겟, MZ 감성, 유머러스한 톤, 전환율 극대화...',
    gen_ad_topup_btn: '광고 보고 무료 충전',
    gen_credits_balance: '보유 {credits} 크레딧',
    gen_credits_cost_range: '1~8 크레딧 소모',
    gen_credits_low_cta: '크레딧이 부족한가요? 30초 광고로 무료 크레딧 받기',
    gen_complete_msg: '{cost} 크레딧 소모 · 잔여 {remaining} 크레딧',
    gen_adblock_title: '광고 차단 프로그램 감지됨',
    gen_adblock_desc: '무료 크레딧을 충전하시려면 광고 차단기(AdBlock)를 잠시 꺼주세요.',
    gen_adblock_dismiss_btn: '껐어요! 광고 보고 크레딧 받기',
    gen_sample_label: '원클릭 샘플:',
    gen_sample_us_tiktok: '미국 틱톡 100만뷰 챌린지',
    gen_sample_yt_shorts: '유튜브 쇼츠 지식창업',
    gen_sample_ig_reels: '인스타 릴스 뷰티',

    // ─── Remix Panel ───
    remix_title: 'AI 리믹스',
    remix_desc: '다른 제품/서비스에 맞게 대본을 재생성합니다.',
    remix_product_placeholder: '새로운 제품/서비스명',
    remix_btn: '리믹스 생성',
    remix_loading: '생성 중...',

    // ─── Misc ───
    loading: '로딩 중...',
    error: '오류가 발생했습니다',
    retry: '다시 시도',
    close: '닫기',
    confirm: '확인',
    cancel: '취소',
  },
  en: {
    // ─── Navbar ───
    nav_generator: 'Script Generator',
    nav_credits: 'Credits',
    nav_trends: 'Latest Trends',
    nav_invite: 'Invite',
    nav_login: 'Login',
    nav_signup: 'Sign Up',
    nav_start_free: 'Start Free',
    nav_my_account: 'My Account',
    nav_logged_in_as: 'Logged in as',
    nav_history: 'Generation History',
    nav_charge: 'Buy Credits',
    nav_settings: 'Account Settings',
    nav_logout: 'Logout',
    nav_mobile_invite: '👥 Invite Friends',
    nav_features: 'Features',
    announcement_bonus: '🎉 Get 10 free credits on signup ·',
    announcement_signup: 'Sign up now',
    credits_label: 'Credits',

    // ─── Hero ───
    hero_tag: 'AI-Powered Short-Form Marketing Analysis',
    hero_title: 'From One Short-Form URL,',
    hero_title2: 'Generate Viral Scripts in 3 Languages',
    hero_desc: 'AI analyzes video structure and creates localized scripts for US, Korea, and Japan markets in under 1 minute.',
    cta_start: 'Start Free',
    cta_credits: 'View Credits',

    // ─── Stats ───
    stats_gen_value: '~2min',
    stats_gen: 'Avg Generation Time',
    stats_locale_value: '3 Countries',
    stats_locale: 'Simultaneous Locales',
    stats_uptime_value: 'Beta',
    stats_uptime: 'Service Status',
    stats_scripts_value: '100+',
    stats_scripts: 'Scripts Generated',

    // ─── Features ───
    features_title: 'Why ViralScript AI?',
    features_desc: 'More than translation. Our AI understands cultural context and viral mechanics across borders.',
    feature_viral_title: 'Viral Structure Analysis',
    feature_viral_desc: 'AI analyzes hook patterns, emotional curves, and transition structures of short-form videos second by second.',
    feature_localize_title: '3-Country Simultaneous Localization',
    feature_localize_desc: 'Instantly generate localized scripts reflecting cultural context and internet memes of Korea, US, and Japan.',
    feature_visual_title: 'AI Visual Storyboard',
    feature_visual_desc: 'Auto-generate video prompts for Runway and Midjourney scene by scene.',
    feature_cache_title: '70% Savings on Cache Hit',
    feature_cache_desc: 'Same URL re-analysis: 3 credits → 1 credit. Smart caching optimized for team collaboration.',

    // ─── Pricing / Free Credits ───
    pricing_title: 'Start For Free',
    pricing_desc: 'Earn free credits via ads, daily roulette, and referrals.',
    free_roulette_title: 'Daily Roulette',
    free_roulette_desc: 'Log in daily and spin the roulette to earn up to 10 credits',
    free_roulette_badge: 'Daily Free',
    free_ad_title: 'Ad Reward Top-Up',
    free_ad_desc: 'Watch a 30-second ad and get 3 free credits instantly (up to 5 times per day)',
    free_ad_badge: '5x per Day',
    free_invite_title: 'Invite Friends',
    free_invite_desc: 'When a friend signs up, you get 3 credits and they get 3 credits',
    free_invite_badge: 'Unlimited',
    recommended: 'Recommended',

    // ─── Footer ───
    footer_disclaimer: 'This platform does not store, transmit, or redistribute original content from submitted URLs. AI-generated results are secondary creative guides for marketing analysis.',
    footer_terms: 'Terms of Service',
    footer_privacy: 'Privacy Policy',

    // ─── Auth Modal ───
    auth_welcome_back: 'Welcome Back',
    auth_nice_to_meet: 'Nice to Meet You! 🎉',
    auth_reset_password: 'Reset Password',
    auth_login_desc: 'Log in to continue',
    auth_signup_desc: 'Sign up now and get 10 free credits instantly ✨',
    auth_forgot_desc: 'Enter your registered email address',
    auth_name_placeholder: 'Name',
    auth_email_placeholder: 'Email Address',
    auth_password_placeholder: 'Password (at least 1 special character)',
    auth_forgot_password_link: 'Forgot password?',
    auth_forgot_email_link: 'Forgot email?',
    auth_login_btn: 'Log In',
    auth_signup_btn: 'Sign Up',
    auth_reset_btn: 'Send Reset Link',
    auth_no_account: "Don't have an account?",
    auth_has_account: 'Already have an account?',
    auth_back_to_login: 'Back to Login',
    auth_free_signup: 'Free Sign Up',
    auth_agree_terms: 'By signing up, you agree to the Terms of Service and Privacy Policy.',
    auth_password_special_char: 'Password must contain at least 1 special character (!@#$%^&*).',
    auth_email_not_confirmed: 'You must verify your email before logging in. Please check your inbox.',
    auth_network_error: 'A network error occurred. Please try again.',
    auth_login_success: 'Login successful! Redirecting...',
    auth_signup_success: 'Signup complete! Please verify your email and log in. 📧',
    auth_email_sent_title: 'Verification Email Sent',
    auth_email_sent_desc: 'A verification email has been sent. Please check your inbox (including spam) and click the confirmation link to complete your registration.',
    auth_email_already_exists: 'This email is already registered.',
    auth_verify_expired: 'Verification time has expired. Please try signing up again from the beginning.',
    auth_resend_email: 'Resend verification email',
    auth_resend_wait: 'Resend available after 1 min',
    auth_email_resent: 'Verification email has been resent.',
    auth_retry_signup: 'Sign Up Again',
    auth_close: 'Close',

    // ─── Find Email ───
    find_email_title: 'Find Email',
    find_email_desc: 'Enter the name and phone number you registered with.',
    find_email_phone_placeholder: 'Phone number (numbers only)',
    find_email_result_label: 'Found Email Account',
    find_email_search_btn: 'Search Email',
    find_email_not_found: 'No matching user information found.',
    find_email_phone_disclaimer: '* Your phone number is used only for finding your email.',
    signup_phone_disclaimer: '* Your phone number is safely used only for account email recovery.',
    terms_label: 'Terms of Service',
    privacy_label: 'Privacy Policy',
    auth_agree_terms_prefix: 'By signing up, you agree to the ',
    auth_agree_terms_suffix: '.',
    and_label: 'and',
    signup_phone_placeholder: 'Phone Number',

    // ─── OTP Email Verification ───
    otp_title: 'Email Verification',
    otp_desc: 'A 6-digit verification code has been sent to {email}',
    otp_placeholder: '6-digit code',
    otp_verify_btn: 'Verify',
    otp_resend_btn: 'Resend Code',
    otp_resend_cooldown: 'Resend in {seconds}s',
    otp_expired: 'Verification code has expired. Please request a new one.',
    otp_invalid: 'The code is incorrect or has expired. Please try again.',
    otp_sending: 'Sending code...',
    otp_verified: 'Verified! Redirecting...',
    otp_change_email: 'Change Email',

    // ─── Daily Reward Wheel ───
    daily_bonus: 'Daily Bonus',
    daily_roulette_title: 'Daily Lucky Roulette',
    daily_roulette_desc: 'Log in every day and get free credits!',
    daily_spin: 'Spin the Wheel',
    daily_claimed: 'Claimed Today',
    daily_result_win: '🎉 You got {amount} credit(s)!',
    daily_result_lose: '😅 No luck! Try again tomorrow',
    daily_1_credit: '1 Credit',
    daily_2_credits: '2 Credits',
    daily_3_credits: '3 Credits',
    daily_5_credits: '5 Credits',
    daily_10_credits: '10 Credits',
    daily_none: 'Miss!',

    // ─── Referral System ───
    referral_title: 'Invite Friends & Earn Credits',
    referral_desc: 'Invite friends and both of you get 3 credits!',
    referral_invited_friends: 'Friends Invited',
    referral_credits_earned: 'Credits Earned',
    referral_max_earn: 'Max Earnings',
    referral_my_code: 'My Referral Code',
    referral_copy_link: 'Copy Invite Link',
    referral_copied: 'Link Copied!',
    referral_share: 'Share',
    referral_kakao: 'KakaoTalk',
    referral_twitter: 'Twitter',
    referral_how: 'How It Works',
    referral_step1_title: 'Share Link',
    referral_step1_desc: 'Send your referral link to friends',
    referral_step2_title: 'Friend Signs Up',
    referral_step2_desc: 'When your friend signs up via your link, they get 3 credits instantly',
    referral_step3_title: 'You Earn 3 Credits',
    referral_step3_desc: 'You also receive 3 credits for every friend who joins',

    // ─── Rewarded Ad Popup ───
    ad_watch_title: 'Watch Ad & Earn Credits',
    ad_watch_desc: 'Watch a 30-second ad and get 3 free credits!',
    ad_watch_btn: 'Watch Ad',
    ad_watching: 'Watching ad...',
    ad_skip: 'Skip',
    ad_complete: 'Watch Complete!',
    ad_claim: 'Claim Credits',
    ad_limit_reached: "You've reached today's ad watch limit. Please try again tomorrow.",
    ad_error: 'An error occurred',

    // ─── Trend Feed ───
    trend_title: 'Global Trends',
    trend_curating: 'AI curating...',
    trend_fallback: 'Fallback Mode',
    trend_filter_all: 'All',
    trend_no_data: 'No trend data yet · Please wait for the first Cron run',
    trend_region_all: 'All Regions',
    trend_region_kr: 'Korea',
    trend_region_us: 'United States',
    trend_region_jp: 'Japan',
    trend_region_cn: 'China',
    trend_load_more: 'Load More',
    trend_views: 'Views',
    trend_likes: 'Likes',
    trend_visit: 'Visit',

    // ─── Trends Page ───
    trends_page_title: 'Real-Time Global Trends',
    trends_page_subtitle: 'Latest Trends',
    trends_page_desc: 'Discover popular short-form content across platforms and analyze them',

    // ─── Pricing Page ───
    pricing_page_title: 'Credit Top-Up Plans',
    pricing_page_desc: 'Top up only when you need. No subscription, no expiration.',
    pricing_page_free_title: 'Start For Free',
    pricing_page_free_desc: 'Earn credits by watching ads and enjoy unlimited analysis.',
    pricing_most_popular: 'Most Popular',
    pricing_charge_btn: 'Top Up',
    pricing_secure: 'Secure Payment',
    pricing_instant: 'Instant Credit',
    pricing_refund: 'Refund Guaranteed',
    pricing_login_prompt: 'Log in and get free credits!',
    pricing_login_desc: 'You can earn free credits through ads, daily roulette, and friend invites.',
    pricing_login_btn: 'Log In & Get Started',
    pricing_roulette_action: 'Spin Roulette',
    pricing_ad_action: 'Watch Ad & Top Up',
    pricing_invite_action: 'Invite',

    // ─── Generator Page ───
    gen_title: 'AI Script Generator',
    gen_subtitle: 'Enter a short-form URL and generate viral scripts in 3 languages',
    gen_url_placeholder: 'Enter short-form URL (TikTok, YouTube Shorts, Instagram Reels)',
    gen_product_placeholder: 'Product/Service to promote (optional)',
    gen_analyze_btn: 'Start Analysis',
    gen_analyzing: 'Analyzing...',
    gen_credits_required: 'Credits Required',
    gen_no_credits: 'Insufficient Credits',
    gen_cached: '⚡ Cached',
    gen_new: '✨ New',
    gen_copy: 'Copy',
    gen_copied: 'Copied',
    gen_remix: 'Remix',
    gen_scenes: 'Scenes',
    gen_scene: 'Scene',
    gen_hook_strategy: 'Hook Strategy',
    gen_script: 'Script',
    gen_ai_prompt: 'AI Video Prompt',
    gen_expand: 'More',
    gen_collapse: 'Collapse',
    gen_login_required: 'Login Required',
    gen_login_desc: 'Please log in or sign up to use this feature.',
    gen_login_btn: 'Log In',
    gen_url_invalid: 'Only YouTube Shorts, TikTok, and Instagram Reels links are supported.',
    gen_url_label: 'Short-Form Video URL',
    gen_product_label: 'Product / Service to promote',
    gen_custom_prompt_label: 'Custom Requests',
    gen_optional: 'Optional',
    gen_custom_prompt_placeholder: 'e.g. Target 20s women, MZ style, humorous tone, maximize conversion...',
    gen_ad_topup_btn: 'Watch Ad & Top Up',
    gen_credits_balance: 'Balance: {credits} credits',
    gen_credits_cost_range: 'uses 1~8 credits',
    gen_credits_low_cta: 'Low on credits? Watch a 30s ad for free credits',
    gen_complete_msg: '{cost} credits used · {remaining} credits remaining',
    gen_adblock_title: 'Ad Blocker Detected',
    gen_adblock_desc: 'To get free credits, please disable your AdBlocker temporarily.',
    gen_adblock_dismiss_btn: 'Turned it off! Watch Ad & Claim',
    gen_sample_label: 'Try a Sample:',
    gen_sample_us_tiktok: 'US TikTok 1M View Challenge',
    gen_sample_yt_shorts: 'YouTube Shorts Knowledge Biz',
    gen_sample_ig_reels: 'Instagram Reels Beauty',

    // ─── Remix Panel ───
    remix_title: 'AI Remix',
    remix_desc: 'Regenerate the script for a different product/service.',
    remix_product_placeholder: 'New product/service name',
    remix_btn: 'Generate Remix',
    remix_loading: 'Generating...',

    // ─── Misc ───
    loading: 'Loading...',
    error: 'An error occurred',
    retry: 'Retry',
    close: 'Close',
    confirm: 'Confirm',
    cancel: 'Cancel',
  },
  zh: {
    // ─── Navbar ───
    nav_generator: '脚本生成器',
    nav_credits: '积分',
    nav_trends: '最新趋势',
    nav_invite: '邀请',
    nav_login: '登录',
    nav_signup: '注册',
    nav_start_free: '免费开始',
    nav_my_account: '我的账户',
    nav_logged_in_as: '已登录',
    nav_history: '生成历史',
    nav_charge: '充值积分',
    nav_settings: '账户设置',
    nav_logout: '退出登录',
    nav_mobile_invite: '👥 邀请好友',
    nav_features: '功能介绍',
    announcement_bonus: '🎉 新用户注册即送10积分 ·',
    announcement_signup: '立即注册',
    credits_label: '积分',

    // ─── Hero ───
    hero_tag: 'AI驱动的短视频营销分析',
    hero_title: '只需一个短视频链接，',
    hero_title2: '生成三种语言的爆款脚本',
    hero_desc: 'AI分析视频结构，为您量身定制面向美国、韩国和日本市场的本土化脚本，一分钟完成。',
    cta_start: '免费开始',
    cta_credits: '查看积分',

    // ─── Stats ───
    stats_gen_value: '约2分钟',
    stats_gen: '平均生成时间',
    stats_locale_value: '3个国家',
    stats_locale: '同步本地化',
    stats_uptime_value: '测试版',
    stats_uptime: '服务状态',
    stats_scripts_value: '100+',
    stats_scripts: '已生成脚本',

    // ─── Features ───
    features_title: '为什么选择ViralScript AI？',
    features_desc: '不止是翻译。我们的AI理解各地文化背景与病毒传播规律。',
    feature_viral_title: '病毒式结构分析',
    feature_viral_desc: 'AI逐秒分析短视频的钩子模式、情感曲线和转场结构。',
    feature_localize_title: '三国同时本地化',
    feature_localize_desc: '即时生成反映韩国、美国、日本文化背景和网络梗的本地化脚本。',
    feature_visual_title: 'AI视觉分镜',
    feature_visual_desc: '为Runway和Midjourney逐场景自动生成视频提示词。',
    feature_cache_title: '缓存命中节省70%',
    feature_cache_desc: '同一URL重新分析：3积分→1积分。为团队协作优化的智能缓存。',

    // ─── Pricing / Free Credits ───
    pricing_title: '免费开始',
    pricing_desc: '通过广告、每日轮盘和邀请好友赚取免费积分。',
    free_roulette_title: '签到轮盘',
    free_roulette_desc: '每日登录并旋转轮盘，赢取最多10积分',
    free_roulette_badge: '每日免费',
    free_ad_title: '广告奖励充值',
    free_ad_desc: '观看30秒广告，立即获得3免费积分（每日最多5次）',
    free_ad_badge: '每日5次',
    free_invite_title: '邀请好友',
    free_invite_desc: '好友注册后，你获得3积分，好友也获得3积分',
    free_invite_badge: '无限',
    recommended: '推荐',

    // ─── Footer ───
    footer_disclaimer: '本平台不存储、传输或重新分发用户提交的URL原始内容。AI生成结果为营销分析的二次创作指南。',
    footer_terms: '服务条款',
    footer_privacy: '隐私政策',

    // ─── Auth Modal ───
    auth_welcome_back: '欢迎回来',
    auth_nice_to_meet: '很高兴见到你！🎉',
    auth_reset_password: '重置密码',
    auth_login_desc: '请登录以继续',
    auth_signup_desc: '立即注册，即刻获得10免费积分 ✨',
    auth_forgot_desc: '请输入注册时使用的邮箱地址',
    auth_name_placeholder: '姓名',
    auth_email_placeholder: '邮箱地址',
    auth_password_placeholder: '密码（至少包含1个特殊字符）',
    auth_forgot_password_link: '忘记密码？',
    auth_forgot_email_link: '忘记邮箱？',
    auth_login_btn: '登录',
    auth_signup_btn: '注册',
    auth_reset_btn: '发送重置链接',
    auth_no_account: '还没有账户？',
    auth_has_account: '已有账户？',
    auth_back_to_login: '返回登录',
    auth_free_signup: '免费注册',
    auth_agree_terms: '注册即表示您同意服务条款和隐私政策。',
    auth_password_special_char: '密码必须包含至少1个特殊字符（!@#$%^&*）。',
    auth_email_not_confirmed: '您需要先验证邮箱才能登录。请查看收件箱。',
    auth_network_error: '网络错误，请重试。',
    auth_login_success: '登录成功！正在跳转...',
    auth_signup_success: '注册完成！请验证邮箱后登录。📧',
    auth_email_sent_title: '验证邮件已发送',
    auth_email_sent_desc: '验证邮件已发送。请检查您的收件箱（包括垃圾邮件），点击确认链接完成注册。',
    auth_email_already_exists: '该邮箱已被注册。',
    auth_verify_expired: '验证时间已过期。请重新开始注册。',
    auth_resend_email: '重新发送验证邮件',
    auth_resend_wait: '1分钟后可重新发送',
    auth_email_resent: '验证邮件已重新发送。',
    auth_retry_signup: '重新注册',
    auth_close: '关闭',

    // ─── Find Email ───
    find_email_title: '查找邮箱',
    find_email_desc: '请输入注册时使用的姓名和电话号码。',
    find_email_phone_placeholder: '电话号码（仅数字）',
    find_email_result_label: '查找到的邮箱账户',
    find_email_search_btn: '查找邮箱',
    find_email_not_found: '未找到匹配的用户信息。',
    find_email_phone_disclaimer: '* 您的电话号码仅用于查找邮箱。',
    signup_phone_disclaimer: '* 您的电话号码将仅安全用于账户邮箱找回。',
    terms_label: '服务条款',
    privacy_label: '隐私政策',
    auth_agree_terms_prefix: '注册即表示您同意',
    auth_agree_terms_suffix: '。',
    and_label: '和',
    signup_phone_placeholder: '电话号码',

    // ─── OTP Email Verification ───
    otp_title: '邮箱验证',
    otp_desc: '6位验证码已发送至 {email}',
    otp_placeholder: '6位验证码',
    otp_verify_btn: '验证',
    otp_resend_btn: '重新发送',
    otp_resend_cooldown: '{seconds}秒后可重新发送',
    otp_expired: '验证码已过期，请重新获取。',
    otp_invalid: '验证码不正确或已过期，请重试。',
    otp_sending: '发送中...',
    otp_verified: '验证成功！正在跳转...',
    otp_change_email: '更换邮箱',

    // ─── Daily Reward Wheel ───
    daily_bonus: '每日奖励',
    daily_roulette_title: '每日幸运轮盘',
    daily_roulette_desc: '每天登录，获取免费积分！',
    daily_spin: '旋转轮盘',
    daily_claimed: '今日已领取',
    daily_result_win: '🎉 获得 {amount} 积分！',
    daily_result_lose: '😅 没中！明天再来',
    daily_1_credit: '1 积分',
    daily_2_credits: '2 积分',
    daily_3_credits: '3 积分',
    daily_5_credits: '5 积分',
    daily_10_credits: '10 积分',
    daily_none: '未中奖',

    // ─── Referral System ───
    referral_title: '邀请好友赚积分',
    referral_desc: '邀请好友，你和好友各得3积分！',
    referral_invited_friends: '已邀请好友',
    referral_credits_earned: '已获积分',
    referral_max_earn: '最高收益',
    referral_my_code: '我的推荐码',
    referral_copy_link: '复制邀请链接',
    referral_copied: '链接已复制！',
    referral_share: '分享',
    referral_kakao: 'KakaoTalk',
    referral_twitter: '推特',
    referral_how: '运作方式',
    referral_step1_title: '分享链接',
    referral_step1_desc: '将推荐链接发送给好友',
    referral_step2_title: '好友注册',
    referral_step2_desc: '好友通过你的链接注册，立即获得3积分',
    referral_step3_title: '你获得3积分',
    referral_step3_desc: '每邀请一位好友，你也获得3积分',

    // ─── Rewarded Ad Popup ───
    ad_watch_title: '观看广告赚积分',
    ad_watch_desc: '观看30秒广告，免费获得3积分！',
    ad_watch_btn: '观看广告',
    ad_watching: '正在观看广告...',
    ad_skip: '跳过',
    ad_complete: '观看完成！',
    ad_claim: '领取积分',
    ad_limit_reached: '今日广告观看次数已达上限。请明天再试。',
    ad_error: '发生错误',

    // ─── Trend Feed ───
    trend_title: '全球趋势',
    trend_curating: 'AI策展中...',
    trend_fallback: '备用模式',
    trend_filter_all: '全部',
    trend_no_data: '暂无趋势数据 · 请等待首次定时任务执行',
    trend_region_all: '全部地区',
    trend_region_kr: '韩国',
    trend_region_us: '美国',
    trend_region_jp: '日本',
    trend_region_cn: '中国',
    trend_load_more: '加载更多',
    trend_views: '观看',
    trend_likes: '点赞',
    trend_visit: '访问',

    // ─── Trends Page ───
    trends_page_title: '实时全球趋势',
    trends_page_subtitle: '最新趋势',
    trends_page_desc: '发现各平台热门短视频并进行分析',

    // ─── Pricing Page ───
    pricing_page_title: '积分充值方案',
    pricing_page_desc: '按需充值。无订阅，不过期。',
    pricing_page_free_title: '免费开始',
    pricing_page_free_desc: '通过观看广告赚取积分，享受无限分析。',
    pricing_most_popular: '最受欢迎',
    pricing_charge_btn: '充值',
    pricing_secure: '安全支付',
    pricing_instant: '即时到账',
    pricing_refund: '退款保障',
    pricing_login_prompt: '登录获取免费积分！',
    pricing_login_desc: '您可以通过广告、每日轮盘和好友邀请赚取免费积分。',
    pricing_login_btn: '登录并开始',
    pricing_roulette_action: '旋转轮盘',
    pricing_ad_action: '观看广告充值',
    pricing_invite_action: '邀请好友',

    // ─── Generator Page ───
    gen_title: 'AI脚本生成器',
    gen_subtitle: '输入短视频链接，生成三种语言的爆款脚本',
    gen_url_placeholder: '输入短视频链接（TikTok、YouTube Shorts、Instagram Reels）',
    gen_product_placeholder: '要推广的产品/服务（可选）',
    gen_analyze_btn: '开始分析',
    gen_analyzing: '分析中...',
    gen_credits_required: '所需积分',
    gen_no_credits: '积分不足',
    gen_cached: '⚡ 已缓存',
    gen_new: '✨ 新生成',
    gen_copy: '复制',
    gen_copied: '已复制',
    gen_remix: '混音',
    gen_scenes: '场景',
    gen_scene: '场景',
    gen_hook_strategy: '钩子策略',
    gen_script: '脚本',
    gen_ai_prompt: 'AI视频提示词',
    gen_expand: '展开',
    gen_collapse: '收起',
    gen_login_required: '请登录后使用',
    gen_login_desc: '请登录或注册以使用此功能。',
    gen_login_btn: '登录',
    gen_url_invalid: '仅支持YouTube Shorts、TikTok和Instagram Reels链接。',
    gen_url_label: '短视频链接',
    gen_product_label: '要推广的产品/服务',
    gen_custom_prompt_label: '额外要求',
    gen_optional: '可选',
    gen_custom_prompt_placeholder: '例：目标20岁女性、MZ风格、幽默语气、最大化转化率...',
    gen_ad_topup_btn: '看广告免费充值',
    gen_credits_balance: '持有 {credits} 积分',
    gen_credits_cost_range: '消耗1~8积分',
    gen_credits_low_cta: '积分不够？观看30秒广告免费获取积分',
    gen_complete_msg: '{cost} 积分已消耗 · 剩余 {remaining} 积分',
    gen_adblock_title: '检测到广告拦截器',
    gen_adblock_desc: '要获取免费积分，请暂时关闭广告拦截器(AdBlock)。',
    gen_adblock_dismiss_btn: '已关闭！观看广告领取积分',
    gen_sample_label: '一键试用：',
    gen_sample_us_tiktok: '美国TikTok百万观看挑战',
    gen_sample_yt_shorts: 'YouTube Shorts知识创业',
    gen_sample_ig_reels: 'Instagram Reels美妆',

    // ─── Remix Panel ───
    remix_title: 'AI混音',
    remix_desc: '为不同产品/服务重新生成脚本。',
    remix_product_placeholder: '新产品/服务名称',
    remix_btn: '生成混音',
    remix_loading: '生成中...',

    // ─── Misc ───
    loading: '加载中...',
    error: '发生错误',
    retry: '重试',
    close: '关闭',
    confirm: '确认',
    cancel: '取消',
  },
  ja: {
    // ─── Navbar ───
    nav_generator: '脚本ジェネレーター',
    nav_credits: 'クレジット',
    nav_trends: '最新トレンド',
    nav_invite: '招待',
    nav_login: 'ログイン',
    nav_signup: '会員登録',
    nav_start_free: '無料で始める',
    nav_my_account: 'マイアカウント',
    nav_logged_in_as: 'ログイン中',
    nav_history: '生成履歴',
    nav_charge: 'クレジット購入',
    nav_settings: 'アカウント設定',
    nav_logout: 'ログアウト',
    nav_mobile_invite: '👥 友達を招待',
    nav_features: '機能紹介',
    announcement_bonus: '🎉 新規登録で10クレジット無料付与 ·',
    announcement_signup: '今すぐ登録',
    credits_label: 'クレジット',

    // ─── Hero ───
    hero_tag: 'AI搭載ショート動画マーケティング分析',
    hero_title: 'ショート動画URLひとつで、',
    hero_title2: '3ヶ国語のバイラル脚本を生成',
    hero_desc: 'AIが動画構造を解析し、米国・韓国・日本市場向けのローカライズ脚本を1分以内に作成します。',
    cta_start: '無料で始める',
    cta_credits: 'クレジットを見る',

    // ─── Stats ───
    stats_gen_value: '約2分',
    stats_gen: '平均生成時間',
    stats_locale_value: '3ヶ国',
    stats_locale: '同時ローカライズ',
    stats_uptime_value: 'ベータ版',
    stats_uptime: 'サービス状態',
    stats_scripts_value: '100+',
    stats_scripts: '生成スクリプト数',

    // ─── Features ───
    features_title: 'ViralScript AIの特長',
    features_desc: '単なる翻訳ではありません。各国のトレンドと感性を理解したAIが本物のバイラルを創ります。',
    feature_viral_title: 'バイラル構造分析',
    feature_viral_desc: 'AIがショート動画のフックパターン、感情曲線、転換構造を秒単位で分析します。',
    feature_localize_title: '3ヶ国同時ローカライズ',
    feature_localize_desc: '韓国・米国・日本の文化的文脈とインターネットミームを反映した現地化脚本を即時生成します。',
    feature_visual_title: 'AIビジュアルコンテ',
    feature_visual_desc: 'Runway、Midjourney用の動画プロンプトをシーンごとに自動生成します。',
    feature_cache_title: 'キャッシュヒットで70%節約',
    feature_cache_desc: '同一URL再分析：3クレジット→1クレジット。チーム協業に最適化されたスマートキャッシング。',

    // ─── Pricing / Free Credits ───
    pricing_title: '無料でスタート',
    pricing_desc: '広告視聴・デイリールーレット・招待で無料クレジットを獲得。',
    free_roulette_title: '出席ルーレット',
    free_roulette_desc: '毎日ログインしてルーレットを回し、最大10クレジットを獲得',
    free_roulette_badge: '毎日無料',
    free_ad_title: '広告報酬チャージ',
    free_ad_desc: '30秒の広告を視聴して即時3クレジットを無料チャージ（1日最大5回）',
    free_ad_badge: '1日5回',
    free_invite_title: '友達招待',
    free_invite_desc: '友達が登録すると、あなたも友達も3クレジット獲得',
    free_invite_badge: '無制限',
    recommended: 'おすすめ',

    // ─── Footer ───
    footer_disclaimer: '本プラットフォームは、ユーザーが提出したURLのオリジナルコンテンツを保存・送信・再配布しません。AI生成結果はマーケティング分析のための二次創作ガイドです。',
    footer_terms: '利用規約',
    footer_privacy: 'プライバシーポリシー',

    // ─── Auth Modal ───
    auth_welcome_back: 'おかえりなさい',
    auth_nice_to_meet: 'はじめまして！🎉',
    auth_reset_password: 'パスワードリセット',
    auth_login_desc: '続行するにはログインしてください',
    auth_signup_desc: '今すぐ登録して10クレジットを無料で獲得 ✨',
    auth_forgot_desc: '登録したメールアドレスを入力してください',
    auth_name_placeholder: '名前',
    auth_email_placeholder: 'メールアドレス',
    auth_password_placeholder: 'パスワード（特殊文字1文字以上含む）',
    auth_forgot_password_link: 'パスワードをお忘れですか？',
    auth_forgot_email_link: 'メールアドレスをお忘れですか？',
    auth_login_btn: 'ログイン',
    auth_signup_btn: '会員登録',
    auth_reset_btn: 'リセットリンクを送信',
    auth_no_account: 'アカウントをお持ちでないですか？',
    auth_has_account: 'すでにアカウントをお持ちですか？',
    auth_back_to_login: 'ログインに戻る',
    auth_free_signup: '無料登録',
    auth_agree_terms: '登録すると、利用規約とプライバシーポリシーに同意したことになります。',
    auth_password_special_char: 'パスワードには少なくとも1つの特殊文字（!@#$%^&*）を含める必要があります。',
    auth_email_not_confirmed: 'ログインする前にメール認証を完了してください。受信トレイをご確認ください。',
    auth_network_error: 'ネットワークエラーが発生しました。もう一度お試しください。',
    auth_login_success: 'ログイン成功！リダイレクト中...',
    auth_signup_success: '登録完了！メール認証後にログインしてください。📧',
    auth_email_sent_title: '認証メール送信完了',
    auth_email_sent_desc: '認証メールが送信されました。受信トレイ（迷惑メールフォルダを含む）から認証リンクをクリックして登録を完了してください。',
    auth_email_already_exists: 'このメールアドレスは既に登録されています。',
    auth_verify_expired: '認証時間が切れました。最初からやり直してください。',
    auth_resend_email: '認証メールを再送信',
    auth_resend_wait: '1分後に再送信可能',
    auth_email_resent: '認証メールが再送信されました。',
    auth_retry_signup: '最初から登録し直す',
    auth_close: '閉じる',

    // ─── Find Email ───
    find_email_title: 'メール検索',
    find_email_desc: '登録時に入力した名前と電話番号を入力してください。',
    find_email_phone_placeholder: '電話番号（数字のみ）',
    find_email_result_label: '検索されたメールアカウント',
    find_email_search_btn: 'メールを検索',
    find_email_not_found: '一致するユーザー情報が見つかりません。',
    find_email_phone_disclaimer: '* 電話番号はメール検索目的でのみ安全に使用されます。',
    signup_phone_disclaimer: '* 電話番号はアカウントのメール検索目的でのみ安全に使用されます。',
    terms_label: '利用規約',
    privacy_label: 'プライバシーポリシー',
    auth_agree_terms_prefix: '登録すると、',
    auth_agree_terms_suffix: 'に同意したことになります。',
    and_label: 'および',
    signup_phone_placeholder: '電話番号',

    // ─── OTP Email Verification ───
    otp_title: 'メール認証',
    otp_desc: '{email}に6桁の認証コードを送信しました',
    otp_placeholder: '6桁の認証コード',
    otp_verify_btn: '認証する',
    otp_resend_btn: 'コードを再送信',
    otp_resend_cooldown: '{seconds}秒後に再送信可能',
    otp_expired: '認証コードの有効期限が切れました。再送信してください。',
    otp_invalid: '認証コードが一致しないか期限切れです。もう一度お試しください。',
    otp_sending: '送信中...',
    otp_verified: '認証完了！リダイレクト中...',
    otp_change_email: 'メールアドレス変更',

    // ─── Daily Reward Wheel ───
    daily_bonus: 'デイリーボーナス',
    daily_roulette_title: 'デイリーラッキールーレット',
    daily_roulette_desc: '毎日ログインして無料クレジットを獲得！',
    daily_spin: 'ルーレットを回す',
    daily_claimed: '本日受取済み',
    daily_result_win: '🎉 {amount}クレジット獲得！',
    daily_result_lose: '😅 ハズレ！明日また挑戦してください',
    daily_1_credit: '1クレジット',
    daily_2_credits: '2クレジット',
    daily_3_credits: '3クレジット',
    daily_5_credits: '5クレジット',
    daily_10_credits: '10クレジット',
    daily_none: 'ハズレ',

    // ─── Referral System ───
    referral_title: '友達を招待してクレジット獲得',
    referral_desc: '友達を招待すると、あなたと友達の両方が3クレジット獲得！',
    referral_invited_friends: '招待した友達',
    referral_credits_earned: '獲得クレジット',
    referral_max_earn: '最大獲得',
    referral_my_code: '紹介コード',
    referral_copy_link: '招待リンクをコピー',
    referral_copied: 'リンクをコピーしました！',
    referral_share: '共有',
    referral_kakao: 'カカオトーク',
    referral_twitter: 'ツイッター',
    referral_how: '仕組み',
    referral_step1_title: 'リンクを共有',
    referral_step1_desc: '友達に紹介リンクを送信',
    referral_step2_title: '友達が登録',
    referral_step2_desc: '友達がリンクから登録すると、即時3クレジット付与',
    referral_step3_title: 'あなたも3クレジット獲得',
    referral_step3_desc: '友達が登録するたびに、あなたにも3クレジットが追加されます',

    // ─── Rewarded Ad Popup ───
    ad_watch_title: '広告を見てクレジット獲得',
    ad_watch_desc: '30秒の広告を視聴して3クレジットを無料獲得！',
    ad_watch_btn: '広告を視聴',
    ad_watching: '広告視聴中...',
    ad_skip: 'スキップ',
    ad_complete: '視聴完了！',
    ad_claim: 'クレジット受取',
    ad_limit_reached: '本日の広告視聴上限に達しました。明日またお試しください。',
    ad_error: 'エラーが発生しました',

    // ─── Trend Feed ───
    trend_title: 'グローバルトレンド',
    trend_curating: 'AIキュレーション中...',
    trend_fallback: 'フォールバックモード',
    trend_filter_all: 'すべて',
    trend_no_data: 'まだトレンドデータがありません · 最初のCron実行までお待ちください',
    trend_region_all: '全地域',
    trend_region_kr: '韓国',
    trend_region_us: 'アメリカ',
    trend_region_jp: '日本',
    trend_region_cn: '中国',
    trend_load_more: 'もっと見る',
    trend_views: '視聴',
    trend_likes: 'いいね',
    trend_visit: 'アクセス',

    // ─── Trends Page ───
    trends_page_title: 'リアルタイムグローバルトレンド',
    trends_page_subtitle: '最新トレンド',
    trends_page_desc: '各プラットフォームの人気ショート動画をチェックして分析しましょう',

    // ─── Pricing Page ───
    pricing_page_title: 'クレジットチャージプラン',
    pricing_page_desc: '必要な時だけチャージ。サブスクなし、有効期限なし。',
    pricing_page_free_title: '無料でスタート',
    pricing_page_free_desc: '広告視聴でクレジットを獲得し、無制限の分析をお楽しみください。',
    pricing_most_popular: '一番人気',
    pricing_charge_btn: 'チャージ',
    pricing_secure: '安全な決済',
    pricing_instant: '即時付与',
    pricing_refund: '返金保証',
    pricing_login_prompt: 'ログインして無料クレジットを獲得！',
    pricing_login_desc: '広告視聴、デイリールーレット、友達招待で無料クレジットを獲得できます。',
    pricing_login_btn: 'ログインして始める',
    pricing_roulette_action: 'ルーレットを回す',
    pricing_ad_action: '広告を見てチャージ',
    pricing_invite_action: '招待する',

    // ─── Generator Page ───
    gen_title: 'AI脚本ジェネレーター',
    gen_subtitle: 'ショート動画URLを入力して3ヶ国語のバイラル脚本を生成',
    gen_url_placeholder: 'ショート動画URLを入力（TikTok、YouTube Shorts、Instagram Reels）',
    gen_product_placeholder: '宣伝する商品/サービス（任意）',
    gen_analyze_btn: '分析開始',
    gen_analyzing: '分析中...',
    gen_credits_required: '必要クレジット',
    gen_no_credits: 'クレジット不足',
    gen_cached: '⚡ キャッシュ済',
    gen_new: '✨ 新規生成',
    gen_copy: 'コピー',
    gen_copied: 'コピー済',
    gen_remix: 'リミックス',
    gen_scenes: 'シーン',
    gen_scene: 'シーン',
    gen_hook_strategy: 'フック戦略',
    gen_script: '脚本',
    gen_ai_prompt: 'AI動画プロンプト',
    gen_expand: 'もっと見る',
    gen_collapse: '折りたたむ',
    gen_login_required: 'ログインが必要です',
    gen_login_desc: 'この機能を使用するにはログインまたは会員登録してください。',
    gen_login_btn: 'ログイン',
    gen_url_invalid: 'YouTube Shorts、TikTok、Instagram Reelsのリンクのみ対応しています。',
    gen_url_label: 'ショート動画URL',
    gen_product_label: '宣伝する商品/サービス',
    gen_custom_prompt_label: '追加リクエスト',
    gen_optional: '任意',
    gen_custom_prompt_placeholder: '例：20代女性ターゲット、MZスタイル、ユーモラスなトーン、コンバージョン最大化...',
    gen_ad_topup_btn: '広告を見てチャージ',
    gen_credits_balance: '保有 {credits} クレジット',
    gen_credits_cost_range: '1~8クレジット消費',
    gen_credits_low_cta: 'クレジットが不足？30秒広告で無料クレジットを獲得',
    gen_complete_msg: '{cost} クレジット消費 · 残り {remaining} クレジット',
    gen_adblock_title: '広告ブロッカーが検出されました',
    gen_adblock_desc: '無料クレジットを獲得するには、広告ブロッカー(AdBlock)を一時的にオフにしてください。',
    gen_adblock_dismiss_btn: 'オフにしました！広告を見てクレジット受取',
    gen_sample_label: 'サンプルを試す：',
    gen_sample_us_tiktok: '米国TikTok 100万再生チャレンジ',
    gen_sample_yt_shorts: 'YouTube Shorts 知識起業',
    gen_sample_ig_reels: 'Instagram Reels 美容',

    // ─── Remix Panel ───
    remix_title: 'AIリミックス',
    remix_desc: '別の商品/サービス向けに脚本を再生成します。',
    remix_product_placeholder: '新しい商品/サービス名',
    remix_btn: 'リミックス生成',
    remix_loading: '生成中...',

    // ─── Misc ───
    loading: '読み込み中...',
    error: 'エラーが発生しました',
    retry: '再試行',
    close: '閉じる',
    confirm: '確認',
    cancel: 'キャンセル',
  },
};

const LANG_KEY = 'viralLang';

export function getLang(): Lang {
  if (typeof window === 'undefined') return 'ko';
  return (localStorage.getItem(LANG_KEY) as Lang) || 'ko';
}

export function t(key: string): string {
  const lang = getLang();
  return T[lang]?.[key] ?? T.ko[key] ?? key;
}

export default function LanguageSwitcher() {
  const [lang, setLang] = useState<Lang>('ko');
  const [isOpen, setIsOpen] = useState(false);

  useEffect(() => {
    setLang(getLang());
  }, []);

  function switchLang(code: Lang) {
    localStorage.setItem(LANG_KEY, code);
    setLang(code);
    setIsOpen(false);
    window.location.reload();
  }

  const current = LANGS.find(l => l.code === lang) ?? LANGS[0];

  return (
    <div className="relative shrink-0">
      <button 
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-2 px-3 sm:px-4 py-2 rounded-xl text-sm font-medium text-white/70 hover:text-white hover:bg-white/8 transition-all border border-white/10 hover:border-white/20 w-[90px] sm:w-[120px] justify-between"
      >
        <div className="flex items-center gap-1.5 sm:gap-2">
          <Globe size={14} className="sm:w-4 sm:h-4" />
          <span className="text-sm sm:text-base">{current.flag}</span>
        </div>
        <svg className={`w-3 h-3 sm:w-4 sm:h-4 transition-transform ${isOpen ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </button>
      {isOpen && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setIsOpen(false)} />
          <div className="absolute right-0 top-full mt-2 w-48 glass-strong rounded-xl overflow-hidden shadow-xl shadow-black/40 fade-in-up z-50">
            {LANGS.map(l => (
              <button
                key={l.code}
                onClick={() => switchLang(l.code)}
                className={`w-full flex items-center gap-3 px-4 py-3 text-sm font-medium transition-all ${l.code === lang ? 'bg-violet-600/40 text-white' : 'text-white/60 hover:text-white hover:bg-white/8'}`}
              >
                <span className="text-xl">{l.flag}</span> 
                <span className="flex-1 text-left">{l.label}</span>
                {l.code === lang && <span className="text-violet-400">✓</span>}
              </button>
            ))}
          </div>
        </>
      )}
    </div>
  );
}