'use client';

import { useState } from 'react';
import { Globe } from 'lucide-react';
import { useLanguage } from './LanguageProvider';

type Lang = 'ko' | 'en' | 'zh' | 'ja';

const LANGS: { code: Lang; label: string; flag: string }[] = [
  { code: 'ko', label: '한국어', flag: '🇰🇷' },
  { code: 'en', label: 'English', flag: '🇺🇸' },
  { code: 'zh', label: '中文', flag: '🇨🇳' },
  { code: 'ja', label: '日本語', flag: '🇯🇵' },
];

// 간단한 번역 테이블
export const T: Record<Lang, Record<string, string>> = {
  ko: {
    settings_hide_password: '비밀번호 숨기기', settings_show_password: '비밀번호 표시', settings_load_failed: '설정을 불러오지 못했습니다.', settings_retry: '다시 불러오기', settings_billing_ready: '크레딧 구매를 이용할 수 있습니다', settings_billing_ready_desc: '크레딧 구매와 결제 상태는 크레딧 페이지에서 확인할 수 있습니다.', settings_manage_credits: '크레딧 관리', ads_temporarily_unavailable: '광고 보상 준비 중', payment_success_refreshing: '결제가 완료되었습니다. 크레딧 잔액을 확인하고 있습니다…', payment_cancelled: '결제가 취소되었습니다.', payment_unavailable: '결제 서비스를 이용할 수 없습니다.', payment_checkout_opening: '결제창 여는 중…', pricing_credit_unit: '크레딧', pricing_generation_count: '최대 {count}회 생성 가능',
    trend_sort_latest: '최신순', trend_sort_popular: '인기순', pricing_credits_balance: '크레딧 {credits}개 보유',
    gen_analysis_heading: '분석할 바이럴 구조', gen_analysis_hook: '첫 1~3초 후킹', gen_analysis_pacing: '장면 구성 속도', gen_analysis_narration: '내레이션 구조', gen_analysis_caption: '자막 패턴', gen_analysis_emotion: '감정 변화', gen_analysis_product: '제품 노출', gen_analysis_cta: '마지막 행동 유도(CTA)',
    gen_language_ko: '한국어', gen_language_en: '영어', gen_language_ja: '일본어', gen_method_live: '실사 촬영', gen_method_ai: 'AI 영상 생성', gen_method_existing: '기존 영상 편집', gen_method_screen: '화면 녹화', gen_method_photo: '사진 또는 이미지 기반', gen_tool_veo: 'Google Veo', gen_tool_runway: 'Runway', gen_tool_kling: 'Kling', gen_tool_firefly: 'Adobe Firefly', gen_tool_generic: '범용 프롬프트',
    gen_content_goal_heading: '콘텐츠 목표', gen_goal_inform: '정보 전달', gen_goal_entertain: '공감과 재미', gen_goal_experience: '경험 공유', gen_goal_story: '이야기 전달', gen_goal_challenge: '챌린지 참여', gen_goal_followers: '팔로워 늘리기', gen_goal_community: '커뮤니티 만들기',
    gen_concept_heading: '콘셉트', gen_concept_problem: '문제 해결', gen_concept_review: '리뷰', gen_concept_before_after: '비포 & 애프터', gen_concept_howto: '방법 안내', gen_concept_emotional: '감성 스토리', gen_concept_comedy: '코미디 또는 밈', gen_concept_vlog: '브이로그', gen_concept_summary: '정보 요약', gen_concept_faceless: '얼굴 없는 콘텐츠',
    gen_mood: '원하는 분위기', gen_mood_placeholder: '예: 밝고, 신뢰감 있고, 활기찬', gen_cast: '출연 방식', gen_cast_on_camera: '직접 출연', gen_cast_faceless: '얼굴 비노출', gen_video_length: '영상 길이', gen_language: '언어', gen_production_method: '제작 방식', gen_ai_tool: 'AI 영상 도구', gen_ai_tool_notice: '영상 생성 API를 호출하지 않습니다. 선택한 도구에 붙여 넣을 프롬프트를 제공합니다.',
    gen_summary_goal: '콘텐츠 목표', gen_summary_duration: '영상 길이', gen_summary_method: '제작 방식', gen_summary_ai_tool: 'AI 도구', gen_summary_scenes: '예상 장면 수', gen_summary_cost: '생성 비용', gen_not_applicable: '해당 없음', gen_cost_value: '생성당 크레딧 8개',
    gen_reference_video: '참고 영상', gen_reference_trend: '트렌드 참고 영상', gen_view_source: '원본 영상 보기', gen_optional_label: '선택 사항', gen_url_placeholder_localized: '선택 사항: YouTube Shorts 또는 TikTok 링크', gen_create_plan: '영상 대본과 장면 만들기', gen_create_plan_cost: '크레딧 8개', gen_creating_plan: '영상 대본과 장면 만드는 중...', gen_advanced_options: '더 자세히 설정하기', gen_advanced_options_desc: '기본 설정으로 바로 만들거나, 영상 스타일을 직접 조정할 수 있어요.', gen_defaults_summary: '기본값: 정보 전달 · 30초 · 실사 촬영', gen_preparing: '준비 중...', gen_analyzing_structure: '영상 구조 분석 중...', gen_analyzing_done: '영상 분석 완료', gen_progress_accessible: '대본 생성 진행률 {progress}%', gen_progress_message: '영상을 확인하고 구조를 분석한 뒤 대본을 생성합니다.',
    settings_tab_profile: '내 프로필', settings_tab_platform: '플랫폼 설정', settings_tab_billing: '결제 및 구독', settings_tab_danger: '위험 구역', settings_title: '설정', settings_subtitle: '프로필, 플랫폼 기본값, 알림 등을 관리합니다', settings_login_title: '로그인이 필요합니다', settings_login_desc: '계정 설정을 변경하려면 먼저 로그인하세요', settings_login: '로그인하기', settings_save: '변경사항 저장', settings_saving: '저장 중...', settings_saved: '저장됐습니다', settings_save_failed: '저장 실패', settings_profile_section: '기본 정보', settings_name: '이름', settings_name_placeholder: '홍길동', settings_email_locked: '이메일 (변경 불가)', settings_security: '보안', settings_password: '비밀번호', settings_password_desc: '현재 비밀번호 확인 후 새 비밀번호로 변경합니다', settings_change: '변경', settings_notifications: '알림 설정', settings_email_notifications: '이메일 알림', settings_notifications_hint: '크레딧 충전, 분석 완료 등 중요 이벤트를 이메일로 수신합니다', settings_password_modal_title: '비밀번호 변경', settings_password_modal_desc: '본인 확인을 위해 현재 비밀번호를 입력하세요.', settings_close: '닫기', settings_current_password: '현재 비밀번호', settings_new_password: '새 비밀번호', settings_confirm_password: '새 비밀번호 확인', settings_password_min: '8자 이상', settings_password_again: '새 비밀번호 다시 입력', settings_cancel: '취소', settings_password_saving: '변경 중...', settings_password_too_short: '새 비밀번호는 8자 이상이어야 합니다.', settings_password_mismatch: '새 비밀번호가 일치하지 않습니다.', settings_current_password_wrong: '현재 비밀번호가 일치하지 않습니다.', settings_password_error: '비밀번호를 변경하지 못했습니다.', settings_password_changed: '비밀번호가 변경되었습니다.', settings_platform_section: '기본 분석 플랫폼', settings_default_platform: '기본 타겟 플랫폼', settings_platform_hint: '분석 결과 생성 시 기본으로 선택될 플랫폼입니다', settings_display: '표시 설정', settings_default_language: '기본 언어', settings_billing_section: '결제 및 구독 관리', settings_billing_soon: 'Phase 3에서 오픈 예정', settings_billing_desc: '구독 플랜 변경, 결제 내역, 인보이스 발행 기능이 곧 추가됩니다', settings_preparing: '준비 중', settings_danger_section: '위험 구역', settings_delete_account: '회원 탈퇴', settings_delete_warning: '탈퇴 시 잔여 크레딧과 생성 기록, 설정이 즉시 삭제되며 복구할 수 없습니다. 같은 이메일로는 탈퇴 후 30일 동안 재가입할 수 없습니다.', settings_confirm_email: '확인을 위해 현재 이메일 입력', settings_delete_working: '탈퇴 처리 중...', settings_delete_permanent: '영구 삭제 및 탈퇴', settings_delete_confirm: '정말로 탈퇴하시겠습니까? 30일간 재가입이 제한됩니다.', settings_delete_error: '회원 탈퇴를 처리하지 못했습니다.',
    history_title: '생성 기록', history_subtitle: '내가 만든 영상 제작 플랜 기록', history_total: '총 {count}개',
    history_login_required: '로그인이 필요합니다', history_login_desc: '히스토리를 보려면 로그인해 주세요', history_login: '로그인하기',
    history_empty: '아직 생성한 제작 플랜이 없습니다.', history_create: '제작 플랜 만들기', history_topic: '주제 기반 생성', history_topic_short: '주제',
    history_video_goal: '영상 목표', history_previous_result: '기존 생성 결과', history_unspecified: '미지정', history_credits: '크레딧 사용',
    history_collapse: '결과 접기', history_view_result: '전체 결과 보기', history_copy_prompt: '영상 프롬프트 복사', history_download_json: '원본 JSON 다운로드',
    history_regenerate: '다시 생성', history_delete: '삭제', history_load_more: '더 보기 ({count}개 남음)', history_old_format: '이전 형식의 결과는 화면에 표시할 수 없습니다. 원본 JSON은 다운로드할 수 있습니다.',
    gen_copy_prompt: '프롬프트 복사', gen_prompt_copied: '프롬프트 복사됨', gen_checking_video: '영상 정보를 확인하는 중...', gen_request_failed: '분석 요청에 실패했습니다. 잠시 후 다시 시도해 주세요.',
    // ─── Navbar ───
    nav_generator: '제작 플랜 만들기',
    nav_credits: '크레딧',
    nav_trends: '최신 트렌드',
    nav_invite: '초대하기',
    nav_login: '로그인',
    nav_signup: '회원가입',
    nav_start_free: '무료로 시작하기',
    nav_my_account: '내 계정',
    nav_logged_in_as: '로그인된 계정',
    nav_history: '생성 히스토리',
    nav_charge: '크레딧 충전',
    nav_settings: '설정',
    nav_logout: '로그아웃',
    nav_mobile_invite: '👥 친구 초대하기',
    nav_features: '기능 소개',
    announcement_bonus: '🎉 신규 가입 시 크레딧 10개 무료 지급 ·',
    announcement_signup: '지금 가입하기',
    credits_label: '크레딧',

    // ─── Hero ───
    hero_tag: 'AI 기반 숏폼 마케팅 분석',
    hero_title: '참고 숏폼 하나로',
    hero_title2: '바이럴 영상 제작 플랜 완성',
    hero_desc: '참고할 숏폼 영상을 입력하면 상품에 맞는 콘셉트, 장면 구성, 내레이션, 자막, AI 영상 프롬프트를 한 번에 만들어드립니다.',
    cta_start: '바이럴 영상 제작 플랜 만들기',
    cta_trends: '최신 트렌드에서 시작하기',
    cta_credits: '크레딧 보기',

    // ─── Stats ───
    stats_gen_value: '약 2분',
    stats_gen: '평균 생성 시간',
    stats_locale_value: '3개국',
    stats_locale: '동시 현지화',
    stats_uptime_value: '베타',
    stats_uptime: '서비스 상태',
    stats_scripts_value: '100+',
    stats_scripts: '생성된 대본',

    // ─── Features ───
    features_title: '재창작 영상 제작에 필요한 모든 것',
    features_desc: '원본을 복제하지 않고 바이럴 구조를 참고해, 상품에 맞는 새 숏폼 제작 플랜을 설계합니다.',
    feature_viral_title: '바이럴 구조 분석',
    feature_viral_desc: 'AI가 숏폼 영상의 후킹 패턴, 감정 곡선, 전환 구조를 초 단위로 분석합니다.',
    feature_concept_title: '상품별 새 콘셉트 제작',
    feature_concept_desc: '상품과 타깃 고객에 맞춘 새로운 콘셉트와 핵심 후킹을 제안합니다.',
    feature_video_prompt_title: 'Veo · Runway · Kling용 프롬프트',
    feature_video_prompt_desc: '각 AI 영상 생성기에 바로 붙여 넣을 수 있는 장면별 프롬프트를 제공합니다.',
    feature_localize_title: '3개국 현지화 대본',
    feature_localize_desc: '한국어·영어·일본어 내레이션과 자막을 제작 목적에 맞춰 설계합니다.',
    feature_editing_title: '장면별 자막 · 효과음 · 편집 타임라인',
    feature_editing_desc: '화면, 카메라, 조명, 제품 노출과 편집 흐름까지 한 번에 계획합니다.',

    // ─── Pricing / Free Credits ───
    pricing_title: '무료로 시작하세요',
    pricing_desc: '광고 시청 · 출석 룰렛 · 친구 초대로 무료 크레딧을 충전하세요',
    free_roulette_title: '출석 룰렛',
    free_roulette_desc: '매일 접속하고 룰렛을 돌려 최대 5 크레딧 획득',
    free_roulette_badge: '매일 무료',
    free_ad_title: '광고 보상 충전',
    free_ad_desc: '30초 광고를 보고 즉시 1 크레딧 무료 충전 (하루 최대 5회)',
    free_ad_badge: '하루 5회',
    free_invite_title: '친구 초대',
    free_invite_desc: '친구가 가입하면 나도 3 크레딧, 친구도 3 크레딧',
    free_invite_badge: '무제한',
    recommended: '추천',

    // ─── Footer ───
    footer_disclaimer: '본 플랫폼은 사용자가 제출한 URL의 원본을 저장·전송·재배포하지 않으며, AI 결과물은 마케팅 분석을 위한 2차 창작 가이드입니다.',
    footer_terms: '이용약관',
    footer_privacy: '개인정보처리방침',
    footer_contact: '문의하기', contact_title: '문의하기', contact_description: '문의 유형과 내용을 남겨 주세요.', contact_category: '문의 유형', contact_category_account: '계정 및 로그인', contact_category_billing: '결제 및 크레딧', contact_category_generation: '영상 제작', contact_category_bug: '오류 신고', contact_category_feature: '기능 제안', contact_category_other: '기타', contact_message: '문의 내용', contact_message_placeholder: '문의 내용을 자세히 작성해 주세요.', contact_message_help: '최소 10자 이상 입력해 주세요.', contact_send: '문의 보내기', contact_sending: '전송 중...', contact_send_error: '문의를 보내지 못했습니다. 잠시 후 다시 시도해 주세요.', contact_login_required: '문의하려면 먼저 로그인해 주세요.', contact_success_title: '문의가 정상적으로 전달되었습니다.', contact_success_description: '확인 후 24시간 이내에 계정 이메일로 답변드리겠습니다.', contact_close: '닫기', auth_suspended_title: '계정이 정지되었습니다', auth_suspended_desc: '이 계정은 현재 로그인할 수 없습니다. 정지 사유를 확인하고 이의 신청을 남길 수 있습니다.', auth_suspended_reason: '정지 사유', auth_suspended_appeal: '정지 이의 신청', auth_suspended_appeal_placeholder: '정지 조치에 대한 설명이나 이의 내용을 작성해 주세요.', auth_suspended_appeal_success: '이의 신청이 전달되었습니다. 확인 후 계정 이메일로 답변드리겠습니다.', auth_suspended_appeal_error: '이의 신청을 보내지 못했습니다. 잠시 후 다시 시도해 주세요.',

    // ─── Auth Modal ───
    auth_welcome_back: '다시 오신 걸 환영해요',
    auth_nice_to_meet: '만나서 반가워요! 🎉',
    auth_reset_password: '비밀번호 재설정',
    auth_login_desc: '계속하려면 로그인해 주세요',
    auth_signup_desc: '지금 가입하고 크레딧 10개를 바로 받아가세요 ✨',
    auth_forgot_desc: '가입한 이메일 주소를 입력해 주세요',
    auth_name_placeholder: '이름',
    auth_email_placeholder: '이메일 주소',
    auth_password_placeholder: '비밀번호 (특수문자 1개 이상 포함)',
    auth_password_minimum: '8자 이상',
    auth_password_special_required: '특수문자 1개 이상',
    auth_forgot_password_link: '비밀번호를 잊으셨나요?',
    auth_forgot_email_link: '이메일을 잊으셨나요?',
    auth_login_btn: '로그인',
    auth_signup_btn: '회원가입 하기',
    auth_reset_btn: '재설정 링크 발송',
    auth_no_account: '계정이 없으신가요?',
    auth_has_account: '이미 계정이 있으신가요?',
    auth_back_to_login: '로그인으로 돌아가기',
    auth_free_signup: '회원가입',
    auth_agree_terms: '가입 시 이용약관 및 개인정보처리방침에 동의합니다.',
    auth_password_special_char: '비밀번호는 최소 1개의 특수문자(!@#$%^&*)를 포함해야 합니다.',
    auth_email_not_confirmed: '이메일 인증을 완료해야 로그인할 수 있습니다. 메일함을 확인해 주세요.',
    auth_network_error: '네트워크 오류가 발생했습니다. 다시 시도해 주세요.',
    auth_login_success: '로그인 성공! 잠시 후 이동합니다.',
    auth_signup_success: '가입 완료! 이메일 인증 후 로그인해 주세요. 📧',
    auth_email_sent_title: '인증 이메일 발송 완료',
    auth_email_sent_desc: '인증 이메일이 발송되었습니다. 이메일 수신함(스팸함 포함)에서 인증 링크를 클릭해 가입을 완료해 주세요.',
    auth_email_already_exists: '이미 가입된 이메일 주소입니다.',
    auth_verify_expired: '인증 시간이 만료되었습니다. 회원가입을 처음부터 다시 시도해 주세요.',
    auth_resend_email: '인증 이메일 재발송',
    auth_resend_wait: '1분 후 재발송 가능',
    auth_email_resent: '인증 이메일이 재발송되었습니다.',
    auth_retry_signup: '처음부터 다시 가입하기',
    auth_close: '닫기',

    // ─── Find Email ───
    find_email_title: '이메일 찾기',
    find_email_desc: '가입 시 등록한 이름과 전화번호를 입력하세요.',
    find_email_phone_placeholder: '전화번호 (숫자만 입력)',
    find_email_result_label: '조회된 이메일 계정',
    find_email_search_btn: '이메일 조회하기',
    find_email_not_found: '일치하는 유저 정보를 찾을 수 없습니다.',
    find_email_phone_disclaimer: '* 전화번호는 계정 이메일 찾기 목적으로만 안전하게 사용됩니다.',
    signup_phone_disclaimer: '* 전화번호는 계정 이메일 찾기 목적으로만 안전하게 사용됩니다.',
    signup_country_label: '국가/지역',
    signup_phone_label: '전화번호',
    terms_label: '이용약관',
    privacy_label: '개인정보처리방침',
    auth_agree_terms_prefix: '가입 시 ',
    auth_agree_terms_suffix: '에 동의합니다.',
    and_label: '및',
    signup_phone_placeholder: '전화번호',

    // ─── OTP Email Verification ───
    otp_title: '이메일 인증',
    otp_desc: '{email}로 6자리 인증번호를 발송했습니다',
    otp_placeholder: '인증번호 6자리',
    otp_verify_btn: '인증 완료',
    otp_resend_btn: '인증번호 재발송',
    otp_resend_cooldown: '{seconds}초 후 재발송 가능',
    otp_expired: '인증번호가 만료되었습니다. 재발송 버튼을 눌러주세요.',
    otp_invalid: '인증번호가 일치하지 않거나 만료되었습니다. 다시 확인해 주세요.',
    otp_sending: '인증번호 발송 중...',
    otp_verified: '인증 완료! 잠시 후 이동합니다.',
    otp_change_email: '이메일 변경',

    // ─── Daily Reward Wheel ───
    daily_bonus: '데일리 보너스',
    daily_roulette_title: '데일리 럭키 룰렛',
    daily_roulette_desc: '매일 로그인하고 무료 크레딧을 받아보세요!',
    daily_spin: '룰렛 돌리기',
    daily_claimed: '오늘 이미 받음',
    daily_result_win: '🎉 {amount} 크레딧 획득!',
    daily_result_lose: '😅 꽝! 내일 다시 도전하세요',
    daily_cooldown_label: '마지막 룰렛 후 24시간까지',
    daily_cooldown_hint: '마지막 룰렛을 돌린 후 24시간이 지나면 다시 돌릴 수 있습니다',
    daily_1_credit: '1 크레딧',
    daily_2_credits: '2 크레딧',
    daily_3_credits: '3 크레딧',
    daily_5_credits: '5 크레딧',
    daily_10_credits: '10 크레딧',
    daily_none: '꽝!',

    // ─── Referral System ───
    referral_signup_label: '추천인 코드 (선택)', referral_signup_placeholder: '추천인 코드 입력', referral_code_invalid: '추천인 코드를 확인할 수 없습니다. 코드를 다시 확인해 주세요.', referral_load_error: '추천인 정보를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.',
    referral_title: '친구 초대하고 크레딧 받기',
    referral_desc: '친구를 초대하면 당신과 친구 모두 3 크레딧을 받습니다!',
    referral_invited_friends: '초대한 친구',
    referral_credits_earned: '받은 크레딧',
    referral_max_earn: '최대 적립',
    referral_my_code: '내 추천인 코드',
    referral_copy_link: '초대 링크 복사하기',
    referral_copied: '링크 복사 완료!',
    referral_share: '공유하기',
    referral_kakao: '카카오톡',
    referral_twitter: '트위터',
    referral_how: '작동 방식',
    referral_step1_title: '링크 공유',
    referral_step1_desc: '친구에게 내 추천 링크를 보내세요',
    referral_step2_title: '친구 가입',
    referral_step2_desc: '친구가 내 링크로 가입하면 3 크레딧 즉시 지급',
    referral_step3_title: '나도 3 크레딧 획득',
    referral_step3_desc: '친구가 가입할 때마다 나에게도 3 크레딧이 추가됩니다',

    // ─── Rewarded Ad Popup ───
    ad_watch_title: '광고 보고 크레딧 받기',
    ad_watch_desc: '30초 광고를 시청하고 1 크레딧을 무료로 받으세요!',
    ad_watch_btn: '광고 시청하기',
    ad_watching: '광고 시청 중...',
    ad_skip: '건너뛰기',
    ad_complete: '시청 완료!',
    ad_claim: '크레딧 받기',
    ad_limit_reached: '오늘 광고 시청 한도에 도달했습니다. 내일 다시 시도해 주세요.',
    ad_error: '오류가 발생했습니다',

    // ─── Trend Feed ───
    trend_title: '글로벌 트렌드',
    trend_curating: 'AI 큐레이팅 중...',
    trend_fallback: 'Fallback 모드',
    trend_filter_all: '전체',
    trend_no_data: '아직 트렌드 데이터가 없습니다',
    trend_region_all: '전체 지역',
    trend_region_kr: '한국',
    trend_region_us: '미국',
    trend_region_jp: '일본',
    trend_region_cn: '중국',
    trend_load_more: '더 보기',
    trend_views: '조회수',
    trend_likes: '좋아요',
    trend_visit: '원본 영상 보기',
    trend_generate: '이 구조로 새 영상 만들기',
    trend_verified: '실제 게시물 확인됨',

    // ─── Trends Page ───
    trends_page_title: '실시간 글로벌 트렌드',
    trends_page_subtitle: '최신 트렌드',
    trends_page_desc: '각 플랫폼의 인기 숏폼을 확인하고 분석해보세요',

    // ─── Pricing Page ───
    pricing_page_title: '크레딧 충전 플랜',
    pricing_page_desc: '필요할 때만 충전하세요. 구독 없음, 만료 없음.',
    pricing_page_free_title: '무료로 시작하세요',
    pricing_page_free_desc: '광고 시청으로 크레딧을 충전하고 무한 분석을 즐기세요.',
    pricing_most_popular: '가장 인기',
    pricing_charge_btn: '충전하기',
    pricing_secure: '안전한 결제 처리',
    pricing_instant: '즉시 크레딧 지급',
    pricing_refund: '환불 정책 보장',
    pricing_login_prompt: '로그인하고 무료 크레딧을 받아보세요!',
    pricing_login_desc: '광고 시청, 출석 룰렛, 친구 초대로 무료 크레딧을 충전할 수 있습니다.',
    pricing_login_btn: '로그인하고 시작하기',
    pricing_roulette_action: '룰렛 돌리기',
    pricing_ad_action: '광고 보고 충전하기',
    pricing_invite_action: '초대하기',

    // ─── Generator Page ───
    gen_title: 'AI 숏폼 영상 만들기',
    gen_subtitle: '주제만 입력하면 영상 대본, 장면 구성, 촬영·편집 가이드를 만들어 드립니다.',
    gen_beginner_guide: '처음이라면 이렇게 생각하면 됩니다. 콘텐츠 주제는 무엇을 보여줄지, 참고 영상은 어떤 영상 흐름을 참고할지 정하는 항목입니다. 참고 영상 없이도 콘텐츠 주제만 입력하면 새 영상 설계안을 만들 수 있습니다.', gen_reference_heading: '참고 영상 입력', gen_reference_desc: 'YouTube Shorts나 TikTok 링크를 선택적으로 입력하세요. 영상 없이도 주제만으로 만들 수 있습니다.', gen_topic_heading: '내 콘텐츠 설정', gen_topic_desc: '만들고 싶은 주제와 영상 스타일을 설정하세요.', gen_topic_label: '콘텐츠 주제', gen_topic_required: '콘텐츠 주제를 입력해 주세요. 예: 초보자를 위한 1인 가구 저녁 레시피', gen_topic_hint: '소개하거나 보여줄 내용을 구체적으로 적어주세요. 예: 초보자를 위한 10분 저녁 레시피', gen_method_heading: '제작 방식 선택', gen_method_desc: '영상 제작에 사용할 방식을 선택하세요.', gen_options_heading: '생성 옵션 확인', gen_options_desc: '입력한 내용을 확인한 뒤 영상 설계안을 생성하세요.', gen_reference_none: '참고 영상 없이 생성', gen_input_required: '입력 필요', gen_previous: '이전 단계', gen_edit_options: '옵션 수정', gen_complete_title: '영상 설계안이 완성되었습니다', gen_complete_desc: '아래 결과를 확인하세요. 생성한 모든 내용은 생성 히스토리에서 다시 볼 수 있습니다.',
    gen_url_placeholder: '숏폼 URL을 입력하세요 (TikTok, YouTube Shorts)',
    gen_product_placeholder: '만들고 싶은 콘텐츠 주제 (선택사항)',
    gen_analyze_btn: '영상 분석 시작',
    gen_analyzing: '분석 중...',
    gen_credits_required: '필요 크레딧',
    gen_no_credits: '크레딧이 부족합니다',
    gen_cached: '⚡ 캐시됨',
    gen_new: '✨ 새로 생성',
    gen_copy: '복사',
    gen_copied: '복사됨',
    gen_remix: '리믹스',
    gen_scenes: 'Scenes',
    gen_scene: 'Scene',
    gen_hook_strategy: 'Hook Strategy',
    gen_script: 'Script',
    gen_ai_prompt: 'AI Video Prompt',
    gen_expand: '더보기',
    gen_collapse: '접기',
    gen_login_required: '서비스 이용 시 로그인이 필요합니다',
    gen_login_desc: '기능을 사용하려면 로그인 또는 회원가입을 해주세요.',
    gen_login_btn: '로그인 하기',
    gen_url_invalid: '유튜브 쇼츠와 틱톡 링크만 분석 가능합니다.',
    gen_url_label: '숏폼 영상 URL',
    gen_product_label: '콘텐츠 주제',
    gen_custom_prompt_label: '추가 요청사항',
    gen_optional: '선택',
    gen_custom_prompt_placeholder: '예: 20대 여성 타겟, MZ 감성, 유머러스한 톤, 전환율 극대화...',
    gen_ad_topup_btn: '광고 보고 무료 충전',
    gen_credits_balance: '보유 {credits} 크레딧',
    gen_credits_cost_range: '생성 1회 8 크레딧',
    gen_credits_low_cta: '크레딧이 부족한가요? 30초 광고로 무료 크레딧 받기',
    gen_complete_msg: '{cost} 크레딧 소모 · 잔여 {remaining} 크레딧',
    gen_adblock_title: '광고 차단 프로그램 감지됨',
    gen_adblock_desc: '무료 크레딧을 충전하시려면 광고 차단기(AdBlock)를 잠시 꺼주세요.',
    gen_adblock_dismiss_btn: '껐어요! 광고 보고 크레딧 받기',
    gen_sample_label: '원클릭 샘플:',
    gen_sample_us_tiktok: '미국 틱톡 100만뷰 챌린지',
    gen_sample_yt_shorts: '유튜브 쇼츠 지식창업',
    plan_create: '바이럴 영상 제작 플랜 만들기', plan_new_from_structure: '이 구조로 새 영상 만들기', plan_view_original: '원본 영상 보기',
    plan_generate_5: '제작 플랜 생성 — 8크레딧', plan_cost_5: '생성 1회 8크레딧', plan_label: '제작 플랜', plan_viral_structure: '바이럴 구조',
    plan_scenes: '장면별 제작 플랜', plan_ai_prompts: 'AI 영상 프롬프트', plan_voice_captions: '음성·자막', plan_editing_timeline: '편집 타임라인',
    plan_copy_veo: 'Veo 프롬프트 복사', plan_copy_runway: 'Runway 프롬프트 복사', plan_copy_kling: 'Kling 프롬프트 복사', plan_copy_generic: '범용 프롬프트 복사',
    plan_copy_all: '전체 결과 복사', plan_download_json: 'JSON 다운로드', plan_original_structure: '원본 구조를 참고한 새 콘텐츠', plan_original_recreation: '원본을 복제하지 않은 재창작 결과',

    // ─── Remix Panel ───
    remix_title: 'AI 리믹스',
    remix_desc: '다른 제품/서비스에 맞게 대본을 재생성합니다.',
    remix_product_placeholder: '새로운 제품/서비스명',
    remix_btn: '리믹스 생성',
    remix_loading: '생성 중...',

    // ─── Misc ───
    loading: '로딩 중...',
    error: '오류가 발생했습니다',
    retry: '다시 시도',
    close: '닫기',
    confirm: '확인',
    cancel: '취소',
  },
  en: {
    settings_hide_password: 'Hide password', settings_show_password: 'Show password', settings_load_failed: 'We could not load your settings.', settings_retry: 'Try again', settings_billing_ready: 'Credit purchases are available', settings_billing_ready_desc: 'Manage credit purchases and payment status on the Credits page.', settings_manage_credits: 'Manage credits', ads_temporarily_unavailable: 'Ad rewards unavailable', payment_success_refreshing: 'Payment completed. Refreshing your credit balance…', payment_cancelled: 'Payment was cancelled.', payment_unavailable: 'Payment checkout is unavailable.', payment_checkout_opening: 'Opening checkout…', pricing_credit_unit: 'credits', pricing_generation_count: 'Up to {count} generations',
    trend_sort_latest: 'Latest', trend_sort_popular: 'Popular', pricing_credits_balance: '{credits} credits available',
    gen_analysis_heading: 'Viral structure to analyze', gen_analysis_hook: 'First 1–3 second hook', gen_analysis_pacing: 'Scene pacing', gen_analysis_narration: 'Narration structure', gen_analysis_caption: 'Caption pattern', gen_analysis_emotion: 'Emotional changes', gen_analysis_product: 'Product visibility', gen_analysis_cta: 'Final CTA',
    gen_language_ko: 'Korean', gen_language_en: 'English', gen_language_ja: 'Japanese', gen_method_live: 'Live action', gen_method_ai: 'AI video generation', gen_method_existing: 'Existing video editing', gen_method_screen: 'Screen recording', gen_method_photo: 'Photo or image based', gen_tool_veo: 'Google Veo', gen_tool_runway: 'Runway', gen_tool_kling: 'Kling', gen_tool_firefly: 'Adobe Firefly', gen_tool_generic: 'Generic prompt',
    gen_content_goal_heading: 'Content goal', gen_goal_inform: 'Inform', gen_goal_entertain: 'Entertain and relate', gen_goal_experience: 'Share an experience', gen_goal_story: 'Tell a story', gen_goal_challenge: 'Join a challenge', gen_goal_followers: 'Grow followers', gen_goal_community: 'Build community',
    gen_concept_heading: 'Concept', gen_concept_problem: 'Problem-solving', gen_concept_review: 'Review', gen_concept_before_after: 'Before and after', gen_concept_howto: 'How-to', gen_concept_emotional: 'Emotional story', gen_concept_comedy: 'Comedy or meme', gen_concept_vlog: 'Vlog', gen_concept_summary: 'Information summary', gen_concept_faceless: 'Faceless content',
    gen_mood: 'Desired mood', gen_mood_placeholder: 'e.g. bright, trustworthy, energetic', gen_cast: 'On-camera talent', gen_cast_on_camera: 'On-camera talent', gen_cast_faceless: 'Faceless', gen_video_length: 'Video length', gen_language: 'Language', gen_production_method: 'Production method', gen_ai_tool: 'AI video tool', gen_ai_tool_notice: 'We do not call a video generation API. We provide copy-ready prompts for your selected tool.',
    gen_summary_goal: 'Content goal', gen_summary_duration: 'Video length', gen_summary_method: 'Production method', gen_summary_ai_tool: 'AI tool', gen_summary_scenes: 'Estimated scenes', gen_summary_cost: 'Generation cost', gen_not_applicable: 'Not applicable', gen_cost_value: '8 credits per generation',
    gen_reference_video: 'Reference video', gen_reference_trend: 'Trend reference video', gen_view_source: 'View source video', gen_optional_label: 'Optional', gen_url_placeholder_localized: 'Optional: YouTube Shorts or TikTok link', gen_create_plan: 'Create script & scenes', gen_create_plan_cost: '8 credits', gen_creating_plan: 'Creating script & scenes...', gen_advanced_options: 'Customize video style', gen_advanced_options_desc: 'Create with the defaults, or adjust the video style yourself.', gen_defaults_summary: 'Defaults: inform · 30 seconds · live action', gen_preparing: 'Preparing...', gen_analyzing_structure: 'Analyzing video structure...', gen_analyzing_done: 'Video analysis complete', gen_progress_accessible: 'Script generation progress {progress}%', gen_progress_message: 'We check the video, analyze its structure, then generate your script.',
    settings_tab_profile: 'My Profile', settings_tab_platform: 'Platform', settings_tab_billing: 'Billing', settings_tab_danger: 'Danger Zone', settings_title: 'Settings', settings_subtitle: 'Manage your profile, platform defaults, and notifications', settings_login_title: 'Login required', settings_login_desc: 'Please log in to change your account settings', settings_login: 'Log in', settings_save: 'Save changes', settings_saving: 'Saving...', settings_saved: 'Saved', settings_save_failed: 'Save failed', settings_profile_section: 'Profile information', settings_name: 'Name', settings_name_placeholder: 'Your name', settings_email_locked: 'Email (cannot be changed)', settings_security: 'Security', settings_password: 'Password', settings_password_desc: 'Verify your current password before setting a new one', settings_change: 'Change', settings_notifications: 'Notifications', settings_email_notifications: 'Email notifications', settings_notifications_hint: 'Receive important updates such as credit top-ups and completed analyses by email', settings_password_modal_title: 'Change password', settings_password_modal_desc: 'Enter your current password to verify your identity.', settings_close: 'Close', settings_current_password: 'Current password', settings_new_password: 'New password', settings_confirm_password: 'Confirm new password', settings_password_min: 'At least 8 characters', settings_password_again: 'Enter the new password again', settings_cancel: 'Cancel', settings_password_saving: 'Changing...', settings_password_too_short: 'The new password must be at least 8 characters.', settings_password_mismatch: 'The new passwords do not match.', settings_current_password_wrong: 'The current password is incorrect.', settings_password_error: 'Could not change the password.', settings_password_changed: 'Password changed successfully.', settings_platform_section: 'Default analysis platform', settings_default_platform: 'Default target platform', settings_platform_hint: 'This platform will be selected by default when generating an analysis', settings_display: 'Display settings', settings_default_language: 'Default language', settings_billing_section: 'Billing and subscription', settings_billing_soon: 'Coming in Phase 3', settings_billing_desc: 'Subscription changes, payment history, and invoices will be available soon', settings_preparing: 'In preparation', settings_danger_section: 'Danger Zone', settings_delete_account: 'Delete account', settings_delete_warning: 'Leaving will permanently delete your remaining credits, generation history, and settings. You cannot sign up again with the same email for 30 days.', settings_confirm_email: 'Enter your current email to confirm', settings_delete_working: 'Deleting account...', settings_delete_permanent: 'Permanently delete account', settings_delete_confirm: 'Are you sure you want to delete your account? Sign-up will be restricted for 30 days.', settings_delete_error: 'Could not process account deletion.',
    history_title: 'Generation History', history_subtitle: 'Your video production plan history', history_total: 'Total: {count}',
    history_login_required: 'Login required', history_login_desc: 'Please log in to view your history', history_login: 'Log in',
    history_empty: 'You have not created a production plan yet.', history_create: 'Create a production plan', history_topic: 'Topic-based generation', history_topic_short: 'Topic',
    history_video_goal: 'Video goal', history_previous_result: 'Previous generation result', history_unspecified: 'Unspecified', history_credits: 'credits used',
    history_collapse: 'Collapse result', history_view_result: 'View full result', history_copy_prompt: 'Copy video prompts', history_download_json: 'Download original JSON',
    history_regenerate: 'Generate again', history_delete: 'Delete', history_load_more: 'Load more ({count} remaining)', history_old_format: 'This result uses an older format and cannot be displayed. You can still download the original JSON.',
    gen_copy_prompt: 'Copy prompt', gen_prompt_copied: 'Prompt copied', gen_checking_video: 'Checking video information...', gen_request_failed: 'The analysis request failed. Please try again shortly.',
    // ─── Navbar ───
    nav_generator: 'Script Generator',
    nav_credits: 'Credits',
    nav_trends: 'Latest Trends',
    nav_invite: 'Invite',
    nav_login: 'Login',
    nav_signup: 'Sign Up',
    nav_start_free: 'Start Free',
    nav_my_account: 'My Account',
    nav_logged_in_as: 'Logged in as',
    nav_history: 'Generation History',
    nav_charge: 'Buy Credits',
    nav_settings: 'Settings',
    nav_logout: 'Logout',
    nav_mobile_invite: '👥 Invite Friends',
    nav_features: 'Features',
    announcement_bonus: '🎉 Get 10 free credits on signup ·',
    announcement_signup: 'Sign up now',
    credits_label: 'Credits',

    // ─── Hero ───
    hero_tag: 'AI-Powered Short-Form Marketing Analysis',
    hero_title: 'From One Short-Form URL,',
    hero_title2: 'Generate Viral Scripts in 3 Languages',
    hero_desc: 'AI analyzes video structure and creates localized scripts for US, Korea, and Japan markets in under 1 minute.',
    cta_start: 'Create a Viral Video Production Plan',
    cta_trends: 'Start from Latest Trends',
    cta_credits: 'View Credits',

    // ─── Stats ───
    stats_gen_value: '~2min',
    stats_gen: 'Avg Generation Time',
    stats_locale_value: '3 Countries',
    stats_locale: 'Simultaneous Locales',
    stats_uptime_value: 'Beta',
    stats_uptime: 'Service Status',
    stats_scripts_value: '100+',
    stats_scripts: 'Scripts Generated',

    // ─── Features ───
    features_title: 'Why ViralScript AI?',
    features_desc: 'More than translation. Our AI understands cultural context and viral mechanics across borders.',
    feature_viral_title: 'Viral Structure Analysis',
    feature_viral_desc: 'AI analyzes hook patterns, emotional curves, and transition structures of short-form videos second by second.',
    feature_localize_title: '3-Country Simultaneous Localization',
    feature_localize_desc: 'Instantly generate localized scripts reflecting cultural context and internet memes of Korea, US, and Japan.',
    feature_visual_title: 'AI Visual Storyboard',
    feature_visual_desc: 'Auto-generate video prompts for Runway and Midjourney scene by scene.',
    feature_cache_title: '70% Savings on Cache Hit',
    feature_cache_desc: 'Same URL re-analysis: 3 credits → 1 credit. Smart caching optimized for team collaboration.',
    feature_concept_title: 'New Product-Specific Concepts',
    feature_concept_desc: 'Create an original concept and core hook tailored to your product and audience.',
    feature_video_prompt_title: 'Prompts for Veo, Runway & Kling',
    feature_video_prompt_desc: 'Get scene-by-scene prompts ready to paste into AI video generators.',
    feature_editing_title: 'Captions, SFX & Editing Timeline',
    feature_editing_desc: 'Plan visuals, camera, lighting, product placement, and editing flow together.',

    // ─── Pricing / Free Credits ───
    pricing_title: 'Start For Free',
    pricing_desc: 'Earn free credits via ads, daily roulette, and referrals.',
    free_roulette_title: 'Daily Roulette',
    free_roulette_desc: 'Log in daily and spin the roulette to earn up to 5 credits',
    free_roulette_badge: 'Daily Free',
    free_ad_title: 'Ad Reward Top-Up',
    free_ad_desc: 'Watch a 30-second ad and get 1 free credit instantly (up to 5 times per day)',
    free_ad_badge: '5x per Day',
    free_invite_title: 'Invite Friends',
    free_invite_desc: 'When a friend signs up, you get 3 credits and they get 3 credits',
    free_invite_badge: 'Unlimited',
    recommended: 'Recommended',

    // ─── Footer ───
    footer_disclaimer: 'This platform does not store, transmit, or redistribute original content from submitted URLs. AI-generated results are secondary creative guides for marketing analysis.',
    footer_terms: 'Terms of Service',
    footer_privacy: 'Privacy Policy',
    footer_contact: 'Contact us', contact_title: 'Contact us', contact_description: 'Choose a category and tell us how we can help.', contact_category: 'Category', contact_category_account: 'Account and sign-in', contact_category_billing: 'Billing and credits', contact_category_generation: 'Video creation', contact_category_bug: 'Report a bug', contact_category_feature: 'Feature request', contact_category_other: 'Other', contact_message: 'Your message', contact_message_placeholder: 'Please describe your inquiry in detail.', contact_message_help: 'Please enter at least 10 characters.', contact_send: 'Send inquiry', contact_sending: 'Sending...', contact_send_error: 'We could not send your inquiry. Please try again later.', contact_login_required: 'Please sign in before sending an inquiry.', contact_success_title: 'Your inquiry has been sent.', contact_success_description: 'We will review it and reply to your account email within 24 hours.', contact_close: 'Close', auth_suspended_title: 'Your account is suspended', auth_suspended_desc: 'This account cannot sign in right now. You can review the reason and submit an appeal.', auth_suspended_reason: 'Reason for suspension', auth_suspended_appeal: 'Submit an appeal', auth_suspended_appeal_placeholder: 'Explain why you are appealing this suspension.', auth_suspended_appeal_success: 'Your appeal has been sent. We will reply to your account email after review.', auth_suspended_appeal_error: 'We could not send your appeal. Please try again later.',

    // ─── Auth Modal ───
    auth_welcome_back: 'Welcome Back',
    auth_nice_to_meet: 'Nice to Meet You! 🎉',
    auth_reset_password: 'Reset Password',
    auth_login_desc: 'Log in to continue',
    auth_signup_desc: 'Sign up now and get 10 free credits instantly ✨',
    auth_forgot_desc: 'Enter your registered email address',
    auth_name_placeholder: 'Name',
    auth_email_placeholder: 'Email Address',
    auth_password_placeholder: 'Password (at least 1 special character)',
    auth_password_minimum: 'At least 8 characters',
    auth_password_special_required: 'At least 1 special character',
    auth_forgot_password_link: 'Forgot password?',
    auth_forgot_email_link: 'Forgot email?',
    auth_login_btn: 'Log In',
    auth_signup_btn: 'Sign Up',
    auth_reset_btn: 'Send Reset Link',
    auth_no_account: "Don't have an account?",
    auth_has_account: 'Already have an account?',
    auth_back_to_login: 'Back to Login',
    auth_free_signup: 'Free Sign Up',
    auth_agree_terms: 'By signing up, you agree to the Terms of Service and Privacy Policy.',
    auth_password_special_char: 'Password must contain at least 1 special character (!@#$%^&*).',
    auth_email_not_confirmed: 'You must verify your email before logging in. Please check your inbox.',
    auth_network_error: 'A network error occurred. Please try again.',
    auth_login_success: 'Login successful! Redirecting...',
    auth_signup_success: 'Signup complete! Please verify your email and log in. 📧',
    auth_email_sent_title: 'Verification Email Sent',
    auth_email_sent_desc: 'A verification email has been sent. Please check your inbox (including spam) and click the confirmation link to complete your registration.',
    auth_email_already_exists: 'This email is already registered.',
    auth_verify_expired: 'Verification time has expired. Please try signing up again from the beginning.',
    auth_resend_email: 'Resend verification email',
    auth_resend_wait: 'Resend available after 1 min',
    auth_email_resent: 'Verification email has been resent.',
    auth_retry_signup: 'Sign Up Again',
    auth_close: 'Close',

    // ─── Find Email ───
    find_email_title: 'Find Email',
    find_email_desc: 'Enter the name and phone number you registered with.',
    find_email_phone_placeholder: 'Phone number (numbers only)',
    find_email_result_label: 'Found Email Account',
    find_email_search_btn: 'Search Email',
    find_email_not_found: 'No matching user information found.',
    find_email_phone_disclaimer: '* Your phone number is used only for finding your email.',
    signup_phone_disclaimer: '* Your phone number is safely used only for account email recovery.',
    signup_country_label: 'Country/region',
    signup_phone_label: 'Phone number',
    terms_label: 'Terms of Service',
    privacy_label: 'Privacy Policy',
    auth_agree_terms_prefix: 'By signing up, you agree to the ',
    auth_agree_terms_suffix: '.',
    and_label: 'and',
    signup_phone_placeholder: 'Phone Number',

    // ─── OTP Email Verification ───
    otp_title: 'Email Verification',
    otp_desc: 'A 6-digit verification code has been sent to {email}',
    otp_placeholder: '6-digit code',
    otp_verify_btn: 'Verify',
    otp_resend_btn: 'Resend Code',
    otp_resend_cooldown: 'Resend in {seconds}s',
    otp_expired: 'Verification code has expired. Please request a new one.',
    otp_invalid: 'The code is incorrect or has expired. Please try again.',
    otp_sending: 'Sending code...',
    otp_verified: 'Verified! Redirecting...',
    otp_change_email: 'Change Email',

    // ─── Daily Reward Wheel ───
    daily_bonus: 'Daily Bonus',
    daily_roulette_title: 'Daily Lucky Roulette',
    daily_roulette_desc: 'Log in every day and get free credits!',
    daily_spin: 'Spin the Wheel',
    daily_claimed: 'Claimed Today',
    daily_result_win: '🎉 You got {amount} credit(s)!',
    daily_result_lose: '😅 No luck! Try again tomorrow',
    daily_cooldown_label: 'Available 24 hours after your last spin',
    daily_cooldown_hint: 'You can spin again 24 hours after your last spin',
    daily_1_credit: '1 Credit',
    daily_2_credits: '2 Credits',
    daily_3_credits: '3 Credits',
    daily_5_credits: '5 Credits',
    daily_10_credits: '10 Credits',
    daily_none: 'Miss!',

    // ─── Referral System ───
    referral_signup_label: 'Referral code (optional)', referral_signup_placeholder: 'Enter a referral code', referral_code_invalid: 'We could not verify that referral code. Please check it and try again.', referral_load_error: 'Could not load referral information. Please try again shortly.',
    referral_title: 'Invite Friends & Earn Credits',
    referral_desc: 'Invite friends and both of you get 3 credits!',
    referral_invited_friends: 'Friends Invited',
    referral_credits_earned: 'Credits Earned',
    referral_max_earn: 'Max Earnings',
    referral_my_code: 'My Referral Code',
    referral_copy_link: 'Copy Invite Link',
    referral_copied: 'Link Copied!',
    referral_share: 'Share',
    referral_kakao: 'KakaoTalk',
    referral_twitter: 'Twitter',
    referral_how: 'How It Works',
    referral_step1_title: 'Share Link',
    referral_step1_desc: 'Send your referral link to friends',
    referral_step2_title: 'Friend Signs Up',
    referral_step2_desc: 'When your friend signs up via your link, they get 3 credits instantly',
    referral_step3_title: 'You Earn 3 Credits',
    referral_step3_desc: 'You also receive 3 credits for every friend who joins',

    // ─── Rewarded Ad Popup ───
    ad_watch_title: 'Watch Ad & Earn Credits',
    ad_watch_desc: 'Watch a 30-second ad and get 1 free credit!',
    ad_watch_btn: 'Watch Ad',
    ad_watching: 'Watching ad...',
    ad_skip: 'Skip',
    ad_complete: 'Watch Complete!',
    ad_claim: 'Claim Credits',
    ad_limit_reached: "You've reached today's ad watch limit. Please try again tomorrow.",
    ad_error: 'An error occurred',

    // ─── Trend Feed ───
    trend_title: 'Global Trends',
    trend_curating: 'AI curating...',
    trend_fallback: 'Fallback Mode',
    trend_filter_all: 'All',
    trend_no_data: 'No trend data yet · Please wait for the first Cron run',
    trend_region_all: 'All Regions',
    trend_region_kr: 'Korea',
    trend_region_us: 'United States',
    trend_region_jp: 'Japan',
    trend_region_cn: 'China',
    trend_load_more: 'Load More',
    trend_views: 'Views',
    trend_likes: 'Likes',
    trend_visit: 'View Original Video',
    trend_generate: 'Create a New Video from This Structure',
    trend_verified: 'Verified Post',

    // ─── Trends Page ───
    trends_page_title: 'Real-Time Global Trends',
    trends_page_subtitle: 'Latest Trends',
    trends_page_desc: 'Discover popular short-form content across platforms and analyze them',

    // ─── Pricing Page ───
    pricing_page_title: 'Credit Top-Up Plans',
    pricing_page_desc: 'Top up only when you need. No subscription, no expiration.',
    pricing_page_free_title: 'Start For Free',
    pricing_page_free_desc: 'Earn credits by watching ads and enjoy unlimited analysis.',
    pricing_most_popular: 'Most Popular',
    pricing_charge_btn: 'Top Up',
    pricing_secure: 'Secure Payment',
    pricing_instant: 'Instant Credit',
    pricing_refund: 'Refund Guaranteed',
    pricing_login_prompt: 'Log in and get free credits!',
    pricing_login_desc: 'You can earn free credits through ads, daily roulette, and friend invites.',
    pricing_login_btn: 'Log In & Get Started',
    pricing_roulette_action: 'Spin Roulette',
    pricing_ad_action: 'Watch Ad & Top Up',
    pricing_invite_action: 'Invite',

    // ─── Generator Page ───
    gen_title: 'Make an AI Short Video',
    gen_subtitle: 'Enter a topic to get a script, scene plan, and filming and editing guide.',
    gen_beginner_guide: 'New here? The content topic is what you want to show, while the reference video is an optional example of the flow you want to study. You can create a new plan with only a topic.', gen_reference_heading: 'Reference Video', gen_reference_desc: 'Optionally add a YouTube Shorts or TikTok link. You can also create a plan from your topic alone.', gen_topic_heading: 'Your Content Settings', gen_topic_desc: 'Set the topic and visual style for your new video.', gen_topic_label: 'Content Topic', gen_topic_required: 'Enter a content topic. Example: 10-minute dinner recipes for busy beginners', gen_topic_hint: 'Describe what you want to show specifically. Example: A quick 10-minute dinner recipe for college students', gen_method_heading: 'Production Method', gen_method_desc: 'Choose how you plan to produce the video.', gen_options_heading: 'Review Generation Options', gen_options_desc: 'Review your inputs before creating the video plan.', gen_reference_none: 'No reference video', gen_input_required: 'Required', gen_previous: 'Previous step', gen_edit_options: 'Edit options', gen_complete_title: 'Your video plan is ready', gen_complete_desc: 'Review the result below. You can find everything again in Generation History.',
    gen_url_placeholder: 'Enter a short-form URL (TikTok or YouTube Shorts)',
    gen_product_placeholder: 'Product/Service to promote (optional)',
    gen_analyze_btn: 'Start Video Analysis',
    gen_analyzing: 'Analyzing...',
    gen_credits_required: 'Credits Required',
    gen_no_credits: 'Insufficient Credits',
    gen_cached: '⚡ Cached',
    gen_new: '✨ New',
    gen_copy: 'Copy',
    gen_copied: 'Copied',
    gen_remix: 'Remix',
    gen_scenes: 'Scenes',
    gen_scene: 'Scene',
    gen_hook_strategy: 'Hook Strategy',
    gen_script: 'Script',
    gen_ai_prompt: 'AI Video Prompt',
    gen_expand: 'More',
    gen_collapse: 'Collapse',
    gen_login_required: 'Login Required',
    gen_login_desc: 'Please log in or sign up to use this feature.',
    gen_login_btn: 'Log In',
    gen_url_invalid: 'Only YouTube Shorts and TikTok links are supported.',
    gen_url_label: 'Short-Form Video URL',
    gen_product_label: 'Product / Service to promote',
    gen_custom_prompt_label: 'Custom Requests',
    gen_optional: 'Optional',
    gen_custom_prompt_placeholder: 'e.g. Target 20s women, MZ style, humorous tone, maximize conversion...',
    gen_ad_topup_btn: 'Watch Ad & Top Up',
    gen_credits_balance: 'Balance: {credits} credits',
    gen_credits_cost_range: '8 credits per generation',
    gen_credits_low_cta: 'Low on credits? Watch a 30s ad for free credits',
    gen_complete_msg: '{cost} credits used · {remaining} credits remaining',
    gen_adblock_title: 'Ad Blocker Detected',
    gen_adblock_desc: 'To get free credits, please disable your AdBlocker temporarily.',
    gen_adblock_dismiss_btn: 'Turned it off! Watch Ad & Claim',
    gen_sample_label: 'Try a Sample:',
    gen_sample_us_tiktok: 'US TikTok 1M View Challenge',
    gen_sample_yt_shorts: 'YouTube Shorts Knowledge Biz',
    plan_create: 'Create a Viral Video Production Plan', plan_new_from_structure: 'Create a New Video from This Structure', plan_view_original: 'View Original Video',
    plan_generate_5: 'Generate Production Plan — 8 Credits', plan_cost_5: '8 Credits per Generation', plan_label: 'Production Plan', plan_viral_structure: 'Viral Structure',
    plan_scenes: 'Scene Production Plan', plan_ai_prompts: 'AI Video Prompts', plan_voice_captions: 'Voice & Captions', plan_editing_timeline: 'Editing Timeline',
    plan_copy_veo: 'Copy Veo Prompt', plan_copy_runway: 'Copy Runway Prompt', plan_copy_kling: 'Copy Kling Prompt', plan_copy_generic: 'Copy Generic Prompt',
    plan_copy_all: 'Copy All Results', plan_download_json: 'Download JSON', plan_original_structure: 'New Content Inspired by the Original Structure', plan_original_recreation: 'A Recreation That Does Not Copy the Original',

    // ─── Remix Panel ───
    remix_title: 'AI Remix',
    remix_desc: 'Regenerate the script for a different product/service.',
    remix_product_placeholder: 'New product/service name',
    remix_btn: 'Generate Remix',
    remix_loading: 'Generating...',

    // ─── Misc ───
    loading: 'Loading...',
    error: 'An error occurred',
    retry: 'Retry',
    close: 'Close',
    confirm: 'Confirm',
    cancel: 'Cancel',
  },
  zh: {
    settings_hide_password: '隐藏密码', settings_show_password: '显示密码', settings_load_failed: '无法加载设置。', settings_retry: '重新加载', settings_billing_ready: '可以购买积分', settings_billing_ready_desc: '请在积分页面管理积分购买和付款状态。', settings_manage_credits: '管理积分', ads_temporarily_unavailable: '广告奖励暂不可用', payment_success_refreshing: '付款已完成，正在刷新积分余额…', payment_cancelled: '付款已取消。', payment_unavailable: '当前无法使用付款服务。', payment_checkout_opening: '正在打开付款页面…', pricing_credit_unit: '积分', pricing_generation_count: '最多可生成 {count} 次',
    trend_sort_latest: '最新', trend_sort_popular: '热门', pricing_credits_balance: '剩余积分：{credits}',
    gen_analysis_heading: '需要分析的热门结构', gen_analysis_hook: '前1–3秒吸引点', gen_analysis_pacing: '镜头节奏', gen_analysis_narration: '旁白结构', gen_analysis_caption: '字幕模式', gen_analysis_emotion: '情绪变化', gen_analysis_product: '产品展示', gen_analysis_cta: '结尾行动号召',
    gen_language_ko: '韩语', gen_language_en: '英语', gen_language_ja: '日语', gen_method_live: '真人拍摄', gen_method_ai: 'AI 视频生成', gen_method_existing: '编辑现有视频', gen_method_screen: '屏幕录制', gen_method_photo: '照片或图片制作', gen_tool_veo: 'Google Veo', gen_tool_runway: 'Runway', gen_tool_kling: 'Kling', gen_tool_firefly: 'Adobe Firefly', gen_tool_generic: '通用提示词',
    gen_content_goal_heading: '内容目标', gen_goal_inform: '传递信息', gen_goal_entertain: '娱乐与共鸣', gen_goal_experience: '分享经历', gen_goal_story: '讲述故事', gen_goal_challenge: '参与挑战', gen_goal_followers: '增加粉丝', gen_goal_community: '建立社群',
    gen_concept_heading: '内容概念', gen_concept_problem: '解决问题', gen_concept_review: '评测', gen_concept_before_after: '前后对比', gen_concept_howto: '教程', gen_concept_emotional: '情感故事', gen_concept_comedy: '喜剧或梗', gen_concept_vlog: '视频日志', gen_concept_summary: '信息摘要', gen_concept_faceless: '不露脸内容',
    gen_mood: '期望风格', gen_mood_placeholder: '例如：明亮、可信、活力', gen_cast: '出镜方式', gen_cast_on_camera: '真人出镜', gen_cast_faceless: '不露脸', gen_video_length: '视频时长', gen_language: '语言', gen_production_method: '制作方式', gen_ai_tool: 'AI 视频工具', gen_ai_tool_notice: '不会调用视频生成 API；我们会提供可直接复制到所选工具的提示词。',
    gen_summary_goal: '内容目标', gen_summary_duration: '视频时长', gen_summary_method: '制作方式', gen_summary_ai_tool: 'AI 工具', gen_summary_scenes: '预计场景数', gen_summary_cost: '生成费用', gen_not_applicable: '不适用', gen_cost_value: '每次生成消耗 8 积分',
    gen_reference_video: '参考视频', gen_reference_trend: '趋势参考视频', gen_view_source: '查看原视频', gen_optional_label: '可选', gen_url_placeholder_localized: '可选：YouTube Shorts 或 TikTok 链接', gen_create_plan: '创建脚本和分镜', gen_create_plan_cost: '8 积分', gen_creating_plan: '正在创建脚本和分镜…', gen_advanced_options: '详细设置', gen_advanced_options_desc: '可直接使用默认设置，也可自行调整视频风格。', gen_defaults_summary: '默认：信息传达 · 30秒 · 实拍', gen_preparing: '准备中…', gen_analyzing_structure: '正在分析视频结构…', gen_analyzing_done: '视频分析完成', gen_progress_accessible: '脚本生成进度 {progress}%', gen_progress_message: '正在检查视频、分析结构并生成脚本。',
    settings_tab_profile: '个人资料', settings_tab_platform: '平台设置', settings_tab_billing: '账单与订阅', settings_tab_danger: '危险区域', settings_title: '设置', settings_subtitle: '管理个人资料、默认平台和通知', settings_login_title: '需要登录', settings_login_desc: '请先登录以更改账户设置', settings_login: '登录', settings_save: '保存更改', settings_saving: '正在保存…', settings_saved: '已保存', settings_save_failed: '保存失败', settings_profile_section: '基本信息', settings_name: '姓名', settings_name_placeholder: '请输入姓名', settings_email_locked: '邮箱（无法更改）', settings_security: '安全', settings_password: '密码', settings_password_desc: '验证当前密码后设置新密码', settings_change: '更改', settings_notifications: '通知设置', settings_email_notifications: '邮件通知', settings_notifications_hint: '通过邮件接收积分充值、分析完成等重要通知', settings_password_modal_title: '更改密码', settings_password_modal_desc: '请输入当前密码以验证身份。', settings_close: '关闭', settings_current_password: '当前密码', settings_new_password: '新密码', settings_confirm_password: '确认新密码', settings_password_min: '至少8个字符', settings_password_again: '再次输入新密码', settings_cancel: '取消', settings_password_saving: '正在更改…', settings_password_too_short: '新密码至少需要8个字符。', settings_password_mismatch: '两次输入的新密码不一致。', settings_current_password_wrong: '当前密码不正确。', settings_password_error: '无法更改密码。', settings_password_changed: '密码已更改。', settings_platform_section: '默认分析平台', settings_default_platform: '默认目标平台', settings_platform_hint: '生成分析结果时将默认选择此平台', settings_display: '显示设置', settings_default_language: '默认语言', settings_billing_section: '账单与订阅管理', settings_billing_soon: '计划于第三阶段开放', settings_billing_desc: '即将支持更改订阅方案、查看付款记录和开具发票', settings_preparing: '准备中', settings_danger_section: '危险区域', settings_delete_account: '注销账户', settings_delete_warning: '注销后，剩余积分、生成记录和设置将立即删除且无法恢复。同一邮箱在30天内无法重新注册。', settings_confirm_email: '请输入当前邮箱以确认', settings_delete_working: '正在注销…', settings_delete_permanent: '永久删除并注销', settings_delete_confirm: '确定要注销吗？30天内将无法重新注册。', settings_delete_error: '无法处理账户注销。',
    history_title: '生成历史', history_subtitle: '我创建的视频制作方案记录', history_total: '共 {count} 条',
    history_login_required: '需要登录', history_login_desc: '请登录以查看历史记录', history_login: '登录',
    history_empty: '你还没有创建制作方案。', history_create: '创建制作方案', history_topic: '基于主题生成', history_topic_short: '主题',
    history_video_goal: '视频目标', history_previous_result: '之前的生成结果', history_unspecified: '未指定', history_credits: '消耗积分',
    history_collapse: '收起结果', history_view_result: '查看完整结果', history_copy_prompt: '复制视频提示词', history_download_json: '下载原始 JSON',
    history_regenerate: '重新生成', history_delete: '删除', history_load_more: '加载更多（剩余 {count} 条）', history_old_format: '此结果使用旧格式，无法显示。仍可下载原始 JSON。',
    gen_copy_prompt: '复制提示词', gen_prompt_copied: '提示词已复制', gen_checking_video: '正在检查视频信息…', gen_request_failed: '分析请求失败，请稍后重试。',
    // ─── Navbar ───
    nav_generator: '脚本生成器',
    nav_credits: '积分',
    nav_trends: '最新趋势',
    nav_invite: '邀请',
    nav_login: '登录',
    nav_signup: '注册',
    nav_start_free: '免费开始',
    nav_my_account: '我的账户',
    nav_logged_in_as: '已登录',
    nav_history: '生成历史',
    nav_charge: '充值积分',
    nav_settings: '设置',
    nav_logout: '退出登录',
    nav_mobile_invite: '👥 邀请好友',
    nav_features: '功能介绍',
    announcement_bonus: '🎉 新用户注册即送10积分 ·',
    announcement_signup: '立即注册',
    credits_label: '积分',

    // ─── Hero ───
    hero_tag: 'AI驱动的短视频营销分析',
    hero_title: '只需一个短视频链接，',
    hero_title2: '生成三种语言的爆款脚本',
    hero_desc: 'AI分析视频结构，为您量身定制面向美国、韩国和日本市场的本土化脚本，一分钟完成。',
    cta_start: '创建爆款视频制作方案',
    cta_trends: '从最新趋势开始',
    cta_credits: '查看积分',

    // ─── Stats ───
    stats_gen_value: '约2分钟',
    stats_gen: '平均生成时间',
    stats_locale_value: '3个国家',
    stats_locale: '同步本地化',
    stats_uptime_value: '测试版',
    stats_uptime: '服务状态',
    stats_scripts_value: '100+',
    stats_scripts: '已生成脚本',

    // ─── Features ───
    features_title: '为什么选择ViralScript AI？',
    features_desc: '不止是翻译。我们的AI理解各地文化背景与病毒传播规律。',
    feature_viral_title: '病毒式结构分析',
    feature_viral_desc: 'AI逐秒分析短视频的钩子模式、情感曲线和转场结构。',
    feature_localize_title: '三国同时本地化',
    feature_localize_desc: '即时生成反映韩国、美国、日本文化背景和网络梗的本地化脚本。',
    feature_visual_title: 'AI视觉分镜',
    feature_visual_desc: '为Runway和Midjourney逐场景自动生成视频提示词。',
    feature_cache_title: '缓存命中节省70%',
    feature_cache_desc: '同一URL重新分析：3积分→1积分。为团队协作优化的智能缓存。',
    feature_concept_title: '按商品打造新概念',
    feature_concept_desc: '根据商品和目标受众打造原创概念与核心钩子。',
    feature_video_prompt_title: 'Veo、Runway、Kling 提示词',
    feature_video_prompt_desc: '提供可直接粘贴到 AI 视频生成器的逐场景提示词。',
    feature_editing_title: '逐场景字幕、音效与剪辑时间线',
    feature_editing_desc: '一次规划画面、镜头、灯光、商品露出与剪辑节奏。',

    // ─── Pricing / Free Credits ───
    pricing_title: '免费开始',
    pricing_desc: '通过广告、每日轮盘和邀请好友赚取免费积分。',
    free_roulette_title: '签到轮盘',
    free_roulette_desc: '每日登录并旋转轮盘，赢取最多5积分',
    free_roulette_badge: '每日免费',
    free_ad_title: '广告奖励充值',
    free_ad_desc: '观看30秒广告，立即获得1免费积分（每日最多5次）',
    free_ad_badge: '每日5次',
    free_invite_title: '邀请好友',
    free_invite_desc: '好友注册后，你获得3积分，好友也获得3积分',
    free_invite_badge: '无限',
    recommended: '推荐',

    // ─── Footer ───
    footer_disclaimer: '本平台不存储、传输或重新分发用户提交的URL原始内容。AI生成结果为营销分析的二次创作指南。',
    footer_terms: '服务条款',
    footer_privacy: '隐私政策',
    footer_contact: '联系我们', contact_title: '联系我们', contact_description: '请选择类别并告诉我们如何帮助您。', contact_category: '咨询类别', contact_category_account: '账户和登录', contact_category_billing: '付款和积分', contact_category_generation: '视频制作', contact_category_bug: '问题反馈', contact_category_feature: '功能建议', contact_category_other: '其他', contact_message: '咨询内容', contact_message_placeholder: '请详细描述您的问题。', contact_message_help: '请至少输入 10 个字符。', contact_send: '发送咨询', contact_sending: '发送中...', contact_send_error: '无法发送咨询，请稍后重试。', contact_login_required: '发送咨询前请先登录。', contact_success_title: '您的咨询已成功发送。', contact_success_description: '我们将在 24 小时内回复至您的账户邮箱。', contact_close: '关闭', auth_suspended_title: '您的账户已被暂停', auth_suspended_desc: '该账户目前无法登录。您可以查看原因并提交申诉。', auth_suspended_reason: '暂停原因', auth_suspended_appeal: '提交申诉', auth_suspended_appeal_placeholder: '请说明您对本次暂停的申诉理由。', auth_suspended_appeal_success: '您的申诉已发送。审核后我们会回复至您的账户邮箱。', auth_suspended_appeal_error: '无法发送申诉，请稍后重试。',

    // ─── Auth Modal ───
    auth_welcome_back: '欢迎回来',
    auth_nice_to_meet: '很高兴见到你！🎉',
    auth_reset_password: '重置密码',
    auth_login_desc: '请登录以继续',
    auth_signup_desc: '立即注册，即刻获得10免费积分 ✨',
    auth_forgot_desc: '请输入注册时使用的邮箱地址',
    auth_name_placeholder: '姓名',
    auth_email_placeholder: '邮箱地址',
    auth_password_placeholder: '密码（至少包含1个特殊字符）',
    auth_password_minimum: '至少 8 个字符',
    auth_password_special_required: '至少 1 个特殊字符',
    auth_forgot_password_link: '忘记密码？',
    auth_forgot_email_link: '忘记邮箱？',
    auth_login_btn: '登录',
    auth_signup_btn: '注册',
    auth_reset_btn: '发送重置链接',
    auth_no_account: '还没有账户？',
    auth_has_account: '已有账户？',
    auth_back_to_login: '返回登录',
    auth_free_signup: '免费注册',
    auth_agree_terms: '注册即表示您同意服务条款和隐私政策。',
    auth_password_special_char: '密码必须包含至少1个特殊字符（!@#$%^&*）。',
    auth_email_not_confirmed: '您需要先验证邮箱才能登录。请查看收件箱。',
    auth_network_error: '网络错误，请重试。',
    auth_login_success: '登录成功！正在跳转...',
    auth_signup_success: '注册完成！请验证邮箱后登录。📧',
    auth_email_sent_title: '验证邮件已发送',
    auth_email_sent_desc: '验证邮件已发送。请检查您的收件箱（包括垃圾邮件），点击确认链接完成注册。',
    auth_email_already_exists: '该邮箱已被注册。',
    auth_verify_expired: '验证时间已过期。请重新开始注册。',
    auth_resend_email: '重新发送验证邮件',
    auth_resend_wait: '1分钟后可重新发送',
    auth_email_resent: '验证邮件已重新发送。',
    auth_retry_signup: '重新注册',
    auth_close: '关闭',

    // ─── Find Email ───
    find_email_title: '查找邮箱',
    find_email_desc: '请输入注册时使用的姓名和电话号码。',
    find_email_phone_placeholder: '电话号码（仅数字）',
    find_email_result_label: '查找到的邮箱账户',
    find_email_search_btn: '查找邮箱',
    find_email_not_found: '未找到匹配的用户信息。',
    find_email_phone_disclaimer: '* 您的电话号码仅用于查找邮箱。',
    signup_phone_disclaimer: '* 您的电话号码将仅安全用于账户邮箱找回。',
    signup_country_label: '国家/地区',
    signup_phone_label: '电话号码',
    terms_label: '服务条款',
    privacy_label: '隐私政策',
    auth_agree_terms_prefix: '注册即表示您同意',
    auth_agree_terms_suffix: '。',
    and_label: '和',
    signup_phone_placeholder: '电话号码',

    // ─── OTP Email Verification ───
    otp_title: '邮箱验证',
    otp_desc: '6位验证码已发送至 {email}',
    otp_placeholder: '6位验证码',
    otp_verify_btn: '验证',
    otp_resend_btn: '重新发送',
    otp_resend_cooldown: '{seconds}秒后可重新发送',
    otp_expired: '验证码已过期，请重新获取。',
    otp_invalid: '验证码不正确或已过期，请重试。',
    otp_sending: '发送中...',
    otp_verified: '验证成功！正在跳转...',
    otp_change_email: '更换邮箱',

    // ─── Daily Reward Wheel ───
    daily_bonus: '每日奖励',
    daily_roulette_title: '每日幸运轮盘',
    daily_roulette_desc: '每天登录，获取免费积分！',
    daily_spin: '旋转轮盘',
    daily_claimed: '今日已领取',
    daily_result_win: '🎉 获得 {amount} 积分！',
    daily_result_lose: '😅 没中！明天再来',
    daily_cooldown_label: '上次旋转后24小时可再次挑战',
    daily_cooldown_hint: '上次旋转满24小时后即可再次挑战',
    daily_1_credit: '1 积分',
    daily_2_credits: '2 积分',
    daily_3_credits: '3 积分',
    daily_5_credits: '5 积分',
    daily_10_credits: '10 积分',
    daily_none: '未中奖',

    // ─── Referral System ───
    referral_signup_label: '推荐码（选填）', referral_signup_placeholder: '输入推荐码', referral_code_invalid: '无法验证此推荐码，请检查后重试。', referral_load_error: '无法加载推荐信息，请稍后重试。',
    referral_title: '邀请好友赚积分',
    referral_desc: '邀请好友，你和好友各得3积分！',
    referral_invited_friends: '已邀请好友',
    referral_credits_earned: '已获积分',
    referral_max_earn: '最高收益',
    referral_my_code: '我的推荐码',
    referral_copy_link: '复制邀请链接',
    referral_copied: '链接已复制！',
    referral_share: '分享',
    referral_kakao: 'KakaoTalk',
    referral_twitter: '推特',
    referral_how: '运作方式',
    referral_step1_title: '分享链接',
    referral_step1_desc: '将推荐链接发送给好友',
    referral_step2_title: '好友注册',
    referral_step2_desc: '好友通过你的链接注册，立即获得3积分',
    referral_step3_title: '你获得3积分',
    referral_step3_desc: '每邀请一位好友，你也获得3积分',

    // ─── Rewarded Ad Popup ───
    ad_watch_title: '观看广告赚积分',
    ad_watch_desc: '观看30秒广告，免费获得1积分！',
    ad_watch_btn: '观看广告',
    ad_watching: '正在观看广告...',
    ad_skip: '跳过',
    ad_complete: '观看完成！',
    ad_claim: '领取积分',
    ad_limit_reached: '今日广告观看次数已达上限。请明天再试。',
    ad_error: '发生错误',

    // ─── Trend Feed ───
    trend_title: '全球趋势',
    trend_curating: 'AI策展中...',
    trend_fallback: '备用模式',
    trend_filter_all: '全部',
    trend_no_data: '暂无趋势数据 · 请等待首次定时任务执行',
    trend_region_all: '全部地区',
    trend_region_kr: '韩国',
    trend_region_us: '美国',
    trend_region_jp: '日本',
    trend_region_cn: '中国',
    trend_load_more: '加载更多',
    trend_views: '观看',
    trend_likes: '点赞',
    trend_visit: '查看原始视频',
    trend_generate: '用此结构制作新视频',
    trend_verified: '已验证真实帖子',

    // ─── Trends Page ───
    trends_page_title: '实时全球趋势',
    trends_page_subtitle: '最新趋势',
    trends_page_desc: '发现各平台热门短视频并进行分析',

    // ─── Pricing Page ───
    pricing_page_title: '积分充值方案',
    pricing_page_desc: '按需充值。无订阅，不过期。',
    pricing_page_free_title: '免费开始',
    pricing_page_free_desc: '通过观看广告赚取积分，享受无限分析。',
    pricing_most_popular: '最受欢迎',
    pricing_charge_btn: '充值',
    pricing_secure: '安全支付',
    pricing_instant: '即时到账',
    pricing_refund: '退款保障',
    pricing_login_prompt: '登录获取免费积分！',
    pricing_login_desc: '您可以通过广告、每日轮盘和好友邀请赚取免费积分。',
    pricing_login_btn: '登录并开始',
    pricing_roulette_action: '旋转轮盘',
    pricing_ad_action: '观看广告充值',
    pricing_invite_action: '邀请好友',

    // ─── Generator Page ───
    gen_title: '制作 AI 短视频',
    gen_subtitle: '输入主题即可获得脚本、分镜以及拍摄和剪辑指南。',
    gen_beginner_guide: '如果你是第一次使用：内容主题是你想展示的内容，参考视频是可选的节奏参考。只输入内容主题也可以生成新方案。', gen_reference_heading: '参考视频', gen_reference_desc: '可选输入 YouTube Shorts 或 TikTok 链接，也可以只根据主题生成方案。', gen_topic_heading: '我的内容设置', gen_topic_desc: '设置新视频的主题和风格。', gen_topic_label: '内容主题', gen_topic_required: '请输入内容主题。例如：适合忙碌新手的十分钟晚餐食谱', gen_topic_hint: '请具体描述要展示的内容。例如：适合大学生的十分钟晚餐食谱', gen_method_heading: '制作方式', gen_method_desc: '选择视频的制作方式。', gen_options_heading: '确认生成选项', gen_options_desc: '确认输入内容后生成视频方案。', gen_reference_none: '不使用参考视频', gen_input_required: '需要输入', gen_previous: '上一步', gen_edit_options: '修改选项', gen_complete_title: '视频方案已完成', gen_complete_desc: '请查看下方结果。所有内容都可以在生成历史中再次查看。',
    gen_url_placeholder: '输入短视频链接（TikTok、YouTube Shorts）',
    gen_product_placeholder: '要推广的产品/服务（可选）',
    gen_analyze_btn: '开始视频分析',
    gen_analyzing: '分析中...',
    gen_credits_required: '所需积分',
    gen_no_credits: '积分不足',
    gen_cached: '⚡ 已缓存',
    gen_new: '✨ 新生成',
    gen_copy: '复制',
    gen_copied: '已复制',
    gen_remix: '混音',
    gen_scenes: '场景',
    gen_scene: '场景',
    gen_hook_strategy: '钩子策略',
    gen_script: '脚本',
    gen_ai_prompt: 'AI视频提示词',
    gen_expand: '展开',
    gen_collapse: '收起',
    gen_login_required: '请登录后使用',
    gen_login_desc: '请登录或注册以使用此功能。',
    gen_login_btn: '登录',
    gen_url_invalid: '仅支持YouTube Shorts和TikTok链接。',
    gen_url_label: '短视频链接',
    gen_product_label: '要推广的产品/服务',
    gen_custom_prompt_label: '额外要求',
    gen_optional: '可选',
    gen_custom_prompt_placeholder: '例：目标20岁女性、MZ风格、幽默语气、最大化转化率...',
    gen_ad_topup_btn: '看广告免费充值',
    gen_credits_balance: '持有 {credits} 积分',
    gen_credits_cost_range: '每次生成消耗8积分',
    gen_credits_low_cta: '积分不够？观看30秒广告免费获取积分',
    gen_complete_msg: '{cost} 积分已消耗 · 剩余 {remaining} 积分',
    gen_adblock_title: '检测到广告拦截器',
    gen_adblock_desc: '要获取免费积分，请暂时关闭广告拦截器(AdBlock)。',
    gen_adblock_dismiss_btn: '已关闭！观看广告领取积分',
    gen_sample_label: '一键试用：',
    gen_sample_us_tiktok: '美国TikTok百万观看挑战',
    gen_sample_yt_shorts: 'YouTube Shorts知识创业',
    plan_create: '创建爆款视频制作方案', plan_new_from_structure: '用此结构制作新视频', plan_view_original: '查看原始视频',
    plan_generate_5: '生成制作方案 — 8积分', plan_cost_5: '每次生成8积分', plan_label: '制作方案', plan_viral_structure: '爆款结构',
    plan_scenes: '逐场景制作方案', plan_ai_prompts: 'AI视频提示词', plan_voice_captions: '语音与字幕', plan_editing_timeline: '剪辑时间线',
    plan_copy_veo: '复制Veo提示词', plan_copy_runway: '复制Runway提示词', plan_copy_kling: '复制Kling提示词', plan_copy_generic: '复制通用提示词',
    plan_copy_all: '复制全部结果', plan_download_json: '下载JSON', plan_original_structure: '参考原始结构的新内容', plan_original_recreation: '未复制原作的再创作结果',

    // ─── Remix Panel ───
    remix_title: 'AI混音',
    remix_desc: '为不同产品/服务重新生成脚本。',
    remix_product_placeholder: '新产品/服务名称',
    remix_btn: '生成混音',
    remix_loading: '生成中...',

    // ─── Misc ───
    loading: '加载中...',
    error: '发生错误',
    retry: '重试',
    close: '关闭',
    confirm: '确认',
    cancel: '取消',
  },
  ja: {
    settings_hide_password: 'パスワードを隠す', settings_show_password: 'パスワードを表示', settings_load_failed: '設定を読み込めませんでした。', settings_retry: '再読み込み', settings_billing_ready: 'クレジットを購入できます', settings_billing_ready_desc: 'クレジットの購入と支払い状況はクレジットページで管理できます。', settings_manage_credits: 'クレジットを管理', ads_temporarily_unavailable: '広告報酬は準備中です', payment_success_refreshing: '支払いが完了しました。クレジット残高を更新しています…', payment_cancelled: '支払いがキャンセルされました。', payment_unavailable: '現在、支払いサービスを利用できません。', payment_checkout_opening: '決済画面を開いています…', pricing_credit_unit: 'クレジット', pricing_generation_count: '最大{count}回生成可能',
    trend_sort_latest: '最新順', trend_sort_popular: '人気順', pricing_credits_balance: '保有クレジット：{credits}',
    gen_analysis_heading: '分析するバイラル構成', gen_analysis_hook: '最初の1〜3秒のフック', gen_analysis_pacing: 'シーンのテンポ', gen_analysis_narration: 'ナレーション構成', gen_analysis_caption: '字幕パターン', gen_analysis_emotion: '感情の変化', gen_analysis_product: '商品露出', gen_analysis_cta: '最後のCTA',
    gen_language_ko: '韓国語', gen_language_en: '英語', gen_language_ja: '日本語', gen_method_live: '実写撮影', gen_method_ai: 'AI動画生成', gen_method_existing: '既存動画の編集', gen_method_screen: '画面録画', gen_method_photo: '写真・画像ベース', gen_tool_veo: 'Google Veo', gen_tool_runway: 'Runway', gen_tool_kling: 'Kling', gen_tool_firefly: 'Adobe Firefly', gen_tool_generic: '汎用プロンプト',
    gen_content_goal_heading: 'コンテンツの目的', gen_goal_inform: '情報を伝える', gen_goal_entertain: '楽しさと共感', gen_goal_experience: '体験を共有', gen_goal_story: '物語を伝える', gen_goal_challenge: 'チャレンジに参加', gen_goal_followers: 'フォロワーを増やす', gen_goal_community: 'コミュニティを作る',
    gen_concept_heading: 'コンセプト', gen_concept_problem: '問題解決', gen_concept_review: 'レビュー', gen_concept_before_after: 'ビフォーアフター', gen_concept_howto: 'ハウツー', gen_concept_emotional: '感情的なストーリー', gen_concept_comedy: 'コメディ・ミーム', gen_concept_vlog: 'Vlog', gen_concept_summary: '情報の要約', gen_concept_faceless: '顔出しなしコンテンツ',
    gen_mood: '希望する雰囲気', gen_mood_placeholder: '例：明るい、信頼感のある、活気ある', gen_cast: '出演スタイル', gen_cast_on_camera: 'カメラ出演', gen_cast_faceless: '顔出しなし', gen_video_length: '動画の長さ', gen_language: '言語', gen_production_method: '制作方法', gen_ai_tool: 'AI動画ツール', gen_ai_tool_notice: '動画生成APIは呼び出しません。選択したツールに貼り付けられるプロンプトを提供します。',
    gen_summary_goal: 'コンテンツの目的', gen_summary_duration: '動画の長さ', gen_summary_method: '制作方法', gen_summary_ai_tool: 'AIツール', gen_summary_scenes: '予定シーン数', gen_summary_cost: '生成コスト', gen_not_applicable: '該当なし', gen_cost_value: '1回の生成につき8クレジット',
    gen_reference_video: '参考動画', gen_reference_trend: 'トレンド参考動画', gen_view_source: '元動画を見る', gen_optional_label: '任意', gen_url_placeholder_localized: '任意：YouTube Shorts または TikTok のリンク', gen_create_plan: '台本とシーンを作成', gen_create_plan_cost: '8クレジット', gen_creating_plan: '台本とシーンを作成中…', gen_advanced_options: '詳しく設定する', gen_advanced_options_desc: '基本設定で作成するか、動画スタイルを自分で調整できます。', gen_defaults_summary: '基本設定：情報提供・30秒・実写撮影', gen_preparing: '準備中…', gen_analyzing_structure: '動画構成を分析中…', gen_analyzing_done: '動画分析が完了しました', gen_progress_accessible: '台本生成の進捗 {progress}%', gen_progress_message: '動画を確認して構成を分析し、台本を生成します。',
    settings_tab_profile: 'プロフィール', settings_tab_platform: 'プラットフォーム', settings_tab_billing: 'お支払い', settings_tab_danger: '危険な操作', settings_title: '設定', settings_subtitle: 'プロフィール、既定のプラットフォーム、通知を管理します', settings_login_title: 'ログインが必要です', settings_login_desc: 'アカウント設定を変更するにはログインしてください', settings_login: 'ログイン', settings_save: '変更を保存', settings_saving: '保存中…', settings_saved: '保存しました', settings_save_failed: '保存に失敗しました', settings_profile_section: '基本情報', settings_name: '名前', settings_name_placeholder: '名前を入力', settings_email_locked: 'メールアドレス（変更不可）', settings_security: 'セキュリティ', settings_password: 'パスワード', settings_password_desc: '現在のパスワードを確認してから新しいパスワードに変更します', settings_change: '変更', settings_notifications: '通知設定', settings_email_notifications: 'メール通知', settings_notifications_hint: 'クレジットの追加や分析完了などの重要な通知をメールで受け取ります', settings_password_modal_title: 'パスワードを変更', settings_password_modal_desc: '本人確認のため現在のパスワードを入力してください。', settings_close: '閉じる', settings_current_password: '現在のパスワード', settings_new_password: '新しいパスワード', settings_confirm_password: '新しいパスワードの確認', settings_password_min: '8文字以上', settings_password_again: '新しいパスワードを再入力', settings_cancel: 'キャンセル', settings_password_saving: '変更中…', settings_password_too_short: '新しいパスワードは8文字以上にしてください。', settings_password_mismatch: '新しいパスワードが一致しません。', settings_current_password_wrong: '現在のパスワードが正しくありません。', settings_password_error: 'パスワードを変更できませんでした。', settings_password_changed: 'パスワードを変更しました。', settings_platform_section: '既定の分析プラットフォーム', settings_default_platform: '既定の対象プラットフォーム', settings_platform_hint: '分析結果の生成時に既定で選択されます', settings_display: '表示設定', settings_default_language: '既定の言語', settings_billing_section: 'お支払いとサブスクリプション', settings_billing_soon: 'フェーズ3で公開予定', settings_billing_desc: 'プラン変更、支払い履歴、請求書発行機能を近日追加します', settings_preparing: '準備中', settings_danger_section: '危険な操作', settings_delete_account: '退会', settings_delete_warning: '退会すると残りのクレジット、生成履歴、設定がすぐに削除され、復元できません。同じメールアドレスでは30日間再登録できません。', settings_confirm_email: '確認のため現在のメールアドレスを入力', settings_delete_working: '退会処理中…', settings_delete_permanent: 'アカウントを完全に削除して退会', settings_delete_confirm: '本当に退会しますか？30日間再登録できません。', settings_delete_error: '退会処理に失敗しました。',
    history_title: '生成履歴', history_subtitle: '作成した動画制作プランの履歴', history_total: '合計 {count} 件',
    history_login_required: 'ログインが必要です', history_login_desc: '履歴を見るにはログインしてください', history_login: 'ログイン',
    history_empty: 'まだ制作プランはありません。', history_create: '制作プランを作成', history_topic: 'テーマから生成', history_topic_short: 'テーマ',
    history_video_goal: '動画の目的', history_previous_result: '以前の生成結果', history_unspecified: '未指定', history_credits: 'クレジット使用',
    history_collapse: '結果を閉じる', history_view_result: '結果をすべて表示', history_copy_prompt: '動画プロンプトをコピー', history_download_json: '元の JSON をダウンロード',
    history_regenerate: '再生成', history_delete: '削除', history_load_more: 'さらに表示（残り {count} 件）', history_old_format: '古い形式のため結果を表示できません。元の JSON はダウンロードできます。',
    gen_copy_prompt: 'プロンプトをコピー', gen_prompt_copied: 'プロンプトをコピーしました', gen_checking_video: '動画情報を確認しています…', gen_request_failed: '分析に失敗しました。しばらくしてから再試行してください。',
    // ─── Navbar ───
    nav_generator: '脚本ジェネレーター',
    nav_credits: 'クレジット',
    nav_trends: '最新トレンド',
    nav_invite: '招待',
    nav_login: 'ログイン',
    nav_signup: '会員登録',
    nav_start_free: '無料で始める',
    nav_my_account: 'マイアカウント',
    nav_logged_in_as: 'ログイン中',
    nav_history: '生成履歴',
    nav_charge: 'クレジット購入',
    nav_settings: '設定',
    nav_logout: 'ログアウト',
    nav_mobile_invite: '👥 友達を招待',
    nav_features: '機能紹介',
    announcement_bonus: '🎉 新規登録で10クレジット無料付与 ·',
    announcement_signup: '今すぐ登録',
    credits_label: 'クレジット',

    // ─── Hero ───
    hero_tag: 'AI搭載ショート動画マーケティング分析',
    hero_title: 'ショート動画URLひとつで、',
    hero_title2: '3ヶ国語のバイラル脚本を生成',
    hero_desc: 'AIが動画構造を解析し、米国・韓国・日本市場向けのローカライズ脚本を1分以内に作成します。',
    cta_start: 'バイラル動画制作プランを作る',
    cta_trends: '最新トレンドから始める',
    cta_credits: 'クレジットを見る',

    // ─── Stats ───
    stats_gen_value: '約2分',
    stats_gen: '平均生成時間',
    stats_locale_value: '3ヶ国',
    stats_locale: '同時ローカライズ',
    stats_uptime_value: 'ベータ版',
    stats_uptime: 'サービス状態',
    stats_scripts_value: '100+',
    stats_scripts: '生成スクリプト数',

    // ─── Features ───
    features_title: 'ViralScript AIの特長',
    features_desc: '単なる翻訳ではありません。各国のトレンドと感性を理解したAIが本物のバイラルを創ります。',
    feature_viral_title: 'バイラル構造分析',
    feature_viral_desc: 'AIがショート動画のフックパターン、感情曲線、転換構造を秒単位で分析します。',
    feature_localize_title: '3ヶ国同時ローカライズ',
    feature_localize_desc: '韓国・米国・日本の文化的文脈とインターネットミームを反映した現地化脚本を即時生成します。',
    feature_visual_title: 'AIビジュアルコンテ',
    feature_visual_desc: 'Runway、Midjourney用の動画プロンプトをシーンごとに自動生成します。',
    feature_cache_title: 'キャッシュヒットで70%節約',
    feature_cache_desc: '同一URL再分析：3クレジット→1クレジット。チーム協業に最適化されたスマートキャッシング。',
    feature_concept_title: '商品別の新コンセプト制作',
    feature_concept_desc: '商品とターゲットに合わせたオリジナルのコンセプトとフックを提案します。',
    feature_video_prompt_title: 'Veo・Runway・Kling用プロンプト',
    feature_video_prompt_desc: 'AI動画生成ツールにすぐ貼り付けられるシーン別プロンプトを提供します。',
    feature_editing_title: 'シーン別字幕・効果音・編集タイムライン',
    feature_editing_desc: '画面、カメラ、照明、商品露出、編集の流れをまとめて計画します。',

    // ─── Pricing / Free Credits ───
    pricing_title: '無料でスタート',
    pricing_desc: '広告視聴・デイリールーレット・招待で無料クレジットを獲得。',
    free_roulette_title: '出席ルーレット',
    free_roulette_desc: '毎日ログインしてルーレットを回し、最大5クレジットを獲得',
    free_roulette_badge: '毎日無料',
    free_ad_title: '広告報酬チャージ',
    free_ad_desc: '30秒の広告を視聴して即時1クレジットを無料チャージ（1日最大5回）',
    free_ad_badge: '1日5回',
    free_invite_title: '友達招待',
    free_invite_desc: '友達が登録すると、あなたも友達も3クレジット獲得',
    free_invite_badge: '無制限',
    recommended: 'おすすめ',

    // ─── Footer ───
    footer_disclaimer: '本プラットフォームは、ユーザーが提出したURLのオリジナルコンテンツを保存・送信・再配布しません。AI生成結果はマーケティング分析のための二次創作ガイドです。',
    footer_terms: '利用規約',
    footer_privacy: 'プライバシーポリシー',
    footer_contact: 'お問い合わせ', contact_title: 'お問い合わせ', contact_description: 'カテゴリーを選び、お問い合わせ内容をお知らせください。', contact_category: 'お問い合わせの種類', contact_category_account: 'アカウント・ログイン', contact_category_billing: '支払い・クレジット', contact_category_generation: '動画作成', contact_category_bug: '不具合報告', contact_category_feature: '機能リクエスト', contact_category_other: 'その他', contact_message: 'お問い合わせ内容', contact_message_placeholder: 'お問い合わせ内容を詳しく入力してください。', contact_message_help: '10文字以上入力してください。', contact_send: 'お問い合わせを送信', contact_sending: '送信中...', contact_send_error: 'お問い合わせを送信できませんでした。後でもう一度お試しください。', contact_success_title: 'お問い合わせを受け付けました。', contact_success_description: '内容を確認後、24時間以内にアカウントのメールアドレスへ返信します。', contact_close: '閉じる', auth_suspended_title: 'アカウントが停止されています', auth_suspended_desc: 'このアカウントは現在ログインできません。理由を確認して異議申し立てを送信できます。', auth_suspended_reason: '停止理由', auth_suspended_appeal: '異議を申し立てる', auth_suspended_appeal_placeholder: '停止に対する異議の内容を入力してください。', auth_suspended_appeal_success: '異議申し立てを受け付けました。確認後、アカウントのメールアドレスへ返信します。', auth_suspended_appeal_error: '異議申し立てを送信できませんでした。後でもう一度お試しください。',

    // ─── Auth Modal ───
    auth_welcome_back: 'おかえりなさい',
    auth_nice_to_meet: 'はじめまして！🎉',
    auth_reset_password: 'パスワードリセット',
    auth_login_desc: '続行するにはログインしてください',
    auth_signup_desc: '今すぐ登録して10クレジットを無料で獲得 ✨',
    auth_forgot_desc: '登録したメールアドレスを入力してください',
    auth_name_placeholder: '名前',
    auth_email_placeholder: 'メールアドレス',
    auth_password_placeholder: 'パスワード（特殊文字1文字以上含む）',
    auth_password_minimum: '8文字以上',
    auth_password_special_required: '特殊文字を1文字以上',
    auth_forgot_password_link: 'パスワードをお忘れですか？',
    auth_forgot_email_link: 'メールアドレスをお忘れですか？',
    auth_login_btn: 'ログイン',
    auth_signup_btn: '会員登録',
    auth_reset_btn: 'リセットリンクを送信',
    auth_no_account: 'アカウントをお持ちでないですか？',
    auth_has_account: 'すでにアカウントをお持ちですか？',
    auth_back_to_login: 'ログインに戻る',
    auth_free_signup: '無料登録',
    auth_agree_terms: '登録すると、利用規約とプライバシーポリシーに同意したことになります。',
    auth_password_special_char: 'パスワードには少なくとも1つの特殊文字（!@#$%^&*）を含める必要があります。',
    auth_email_not_confirmed: 'ログインする前にメール認証を完了してください。受信トレイをご確認ください。',
    auth_network_error: 'ネットワークエラーが発生しました。もう一度お試しください。',
    auth_login_success: 'ログイン成功！リダイレクト中...',
    auth_signup_success: '登録完了！メール認証後にログインしてください。📧',
    auth_email_sent_title: '認証メール送信完了',
    auth_email_sent_desc: '認証メールが送信されました。受信トレイ（迷惑メールフォルダを含む）から認証リンクをクリックして登録を完了してください。',
    auth_email_already_exists: 'このメールアドレスは既に登録されています。',
    auth_verify_expired: '認証時間が切れました。最初からやり直してください。',
    auth_resend_email: '認証メールを再送信',
    auth_resend_wait: '1分後に再送信可能',
    auth_email_resent: '認証メールが再送信されました。',
    auth_retry_signup: '最初から登録し直す',
    auth_close: '閉じる',

    // ─── Find Email ───
    find_email_title: 'メール検索',
    find_email_desc: '登録時に入力した名前と電話番号を入力してください。',
    find_email_phone_placeholder: '電話番号（数字のみ）',
    find_email_result_label: '検索されたメールアカウント',
    find_email_search_btn: 'メールを検索',
    find_email_not_found: '一致するユーザー情報が見つかりません。',
    find_email_phone_disclaimer: '* 電話番号はメール検索目的でのみ安全に使用されます。',
    signup_phone_disclaimer: '* 電話番号はアカウントのメール検索目的でのみ安全に使用されます。',
    signup_country_label: '国/地域',
    signup_phone_label: '電話番号',
    terms_label: '利用規約',
    privacy_label: 'プライバシーポリシー',
    auth_agree_terms_prefix: '登録すると、',
    auth_agree_terms_suffix: 'に同意したことになります。',
    and_label: 'および',
    signup_phone_placeholder: '電話番号',

    // ─── OTP Email Verification ───
    otp_title: 'メール認証',
    otp_desc: '{email}に6桁の認証コードを送信しました',
    otp_placeholder: '6桁の認証コード',
    otp_verify_btn: '認証する',
    otp_resend_btn: 'コードを再送信',
    otp_resend_cooldown: '{seconds}秒後に再送信可能',
    otp_expired: '認証コードの有効期限が切れました。再送信してください。',
    otp_invalid: '認証コードが一致しないか期限切れです。もう一度お試しください。',
    otp_sending: '送信中...',
    otp_verified: '認証完了！リダイレクト中...',
    otp_change_email: 'メールアドレス変更',

    // ─── Daily Reward Wheel ───
    daily_bonus: 'デイリーボーナス',
    daily_roulette_title: 'デイリーラッキールーレット',
    daily_roulette_desc: '毎日ログインして無料クレジットを獲得！',
    daily_spin: 'ルーレットを回す',
    daily_claimed: '本日受取済み',
    daily_result_win: '🎉 {amount}クレジット獲得！',
    daily_result_lose: '😅 ハズレ！明日また挑戦してください',
    daily_cooldown_label: '前回のスピンから24時間後に再挑戦できます',
    daily_cooldown_hint: '前回のルーレットから24時間経過すると再挑戦できます',
    daily_1_credit: '1クレジット',
    daily_2_credits: '2クレジット',
    daily_3_credits: '3クレジット',
    daily_5_credits: '5クレジット',
    daily_10_credits: '10クレジット',
    daily_none: 'ハズレ',

    // ─── Referral System ───
    referral_signup_label: '紹介コード（任意）', referral_signup_placeholder: '紹介コードを入力', referral_code_invalid: '紹介コードを確認できません。コードを確認して再試行してください。', referral_load_error: '紹介情報を読み込めませんでした。しばらくしてから再試行してください。',
    referral_title: '友達を招待してクレジット獲得',
    referral_desc: '友達を招待すると、あなたと友達の両方が3クレジット獲得！',
    referral_invited_friends: '招待した友達',
    referral_credits_earned: '獲得クレジット',
    referral_max_earn: '最大獲得',
    referral_my_code: '紹介コード',
    referral_copy_link: '招待リンクをコピー',
    referral_copied: 'リンクをコピーしました！',
    referral_share: '共有',
    referral_kakao: 'カカオトーク',
    referral_twitter: 'ツイッター',
    referral_how: '仕組み',
    referral_step1_title: 'リンクを共有',
    referral_step1_desc: '友達に紹介リンクを送信',
    referral_step2_title: '友達が登録',
    referral_step2_desc: '友達がリンクから登録すると、即時3クレジット付与',
    referral_step3_title: 'あなたも3クレジット獲得',
    referral_step3_desc: '友達が登録するたびに、あなたにも3クレジットが追加されます',

    // ─── Rewarded Ad Popup ───
    ad_watch_title: '広告を見てクレジット獲得',
    ad_watch_desc: '30秒の広告を視聴して1クレジットを無料獲得！',
    ad_watch_btn: '広告を視聴',
    ad_watching: '広告視聴中...',
    ad_skip: 'スキップ',
    ad_complete: '視聴完了！',
    ad_claim: 'クレジット受取',
    ad_limit_reached: '本日の広告視聴上限に達しました。明日またお試しください。',
    ad_error: 'エラーが発生しました',

    // ─── Trend Feed ───
    trend_title: 'グローバルトレンド',
    trend_curating: 'AIキュレーション中...',
    trend_fallback: 'フォールバックモード',
    trend_filter_all: 'すべて',
    trend_no_data: 'まだトレンドデータがありません · 最初のCron実行までお待ちください',
    trend_region_all: '全地域',
    trend_region_kr: '韓国',
    trend_region_us: 'アメリカ',
    trend_region_jp: '日本',
    trend_region_cn: '中国',
    trend_load_more: 'もっと見る',
    trend_views: '視聴',
    trend_likes: 'いいね',
    trend_visit: '元動画を見る',
    trend_generate: 'この構造で新しい動画を作る',
    trend_verified: '実在する投稿を確認済み',

    // ─── Trends Page ───
    trends_page_title: 'リアルタイムグローバルトレンド',
    trends_page_subtitle: '最新トレンド',
    trends_page_desc: '各プラットフォームの人気ショート動画をチェックして分析しましょう',

    // ─── Pricing Page ───
    pricing_page_title: 'クレジットチャージプラン',
    pricing_page_desc: '必要な時だけチャージ。サブスクなし、有効期限なし。',
    pricing_page_free_title: '無料でスタート',
    pricing_page_free_desc: '広告視聴でクレジットを獲得し、無制限の分析をお楽しみください。',
    pricing_most_popular: '一番人気',
    pricing_charge_btn: 'チャージ',
    pricing_secure: '安全な決済',
    pricing_instant: '即時付与',
    pricing_refund: '返金保証',
    pricing_login_prompt: 'ログインして無料クレジットを獲得！',
    pricing_login_desc: '広告視聴、デイリールーレット、友達招待で無料クレジットを獲得できます。',
    pricing_login_btn: 'ログインして始める',
    pricing_roulette_action: 'ルーレットを回す',
    pricing_ad_action: '広告を見てチャージ',
    pricing_invite_action: '招待する',

    // ─── Generator Page ───
    gen_title: 'AIショート動画を作る',
    gen_subtitle: 'テーマを入力するだけで、台本、シーン構成、撮影・編集ガイドを作成します。',
    gen_beginner_guide: '初めての方へ：コンテンツテーマは見せたい内容、参考動画は流れを学ぶための任意の例です。テーマだけでも新しいプランを作成できます。', gen_reference_heading: '参考動画', gen_reference_desc: 'YouTube ShortsまたはTikTokのリンクを任意で入力できます。テーマだけでも作成できます。', gen_topic_heading: 'コンテンツ設定', gen_topic_desc: '新しい動画のテーマとスタイルを設定します。', gen_topic_label: 'コンテンツテーマ', gen_topic_required: 'コンテンツテーマを入力してください。例：忙しい初心者向け10分夕食レシピ', gen_topic_hint: '見せたい内容を具体的に書いてください。例：大学生向けの10分夕食レシピ', gen_method_heading: '制作方法', gen_method_desc: '動画の制作方法を選択します。', gen_options_heading: '生成オプションの確認', gen_options_desc: '入力内容を確認して動画プランを作成します。', gen_reference_none: '参考動画なし', gen_input_required: '入力が必要', gen_previous: '前のステップ', gen_edit_options: 'オプションを編集', gen_complete_title: '動画プランが完成しました', gen_complete_desc: '下の結果を確認してください。すべての内容は生成履歴から再確認できます。',
    gen_url_placeholder: 'ショート動画URLを入力（TikTok、YouTube Shorts）',
    gen_product_placeholder: '宣伝する商品/サービス（任意）',
    gen_analyze_btn: '動画分析を開始',
    gen_analyzing: '分析中...',
    gen_credits_required: '必要クレジット',
    gen_no_credits: 'クレジット不足',
    gen_cached: '⚡ キャッシュ済',
    gen_new: '✨ 新規生成',
    gen_copy: 'コピー',
    gen_copied: 'コピー済',
    gen_remix: 'リミックス',
    gen_scenes: 'シーン',
    gen_scene: 'シーン',
    gen_hook_strategy: 'フック戦略',
    gen_script: '脚本',
    gen_ai_prompt: 'AI動画プロンプト',
    gen_expand: 'もっと見る',
    gen_collapse: '折りたたむ',
    gen_login_required: 'ログインが必要です',
    gen_login_desc: 'この機能を使用するにはログインまたは会員登録してください。',
    gen_login_btn: 'ログイン',
    gen_url_invalid: 'YouTube ShortsとTikTokのリンクのみ対応しています。',
    gen_url_label: 'ショート動画URL',
    gen_product_label: '宣伝する商品/サービス',
    gen_custom_prompt_label: '追加リクエスト',
    gen_optional: '任意',
    gen_custom_prompt_placeholder: '例：20代女性ターゲット、MZスタイル、ユーモラスなトーン、コンバージョン最大化...',
    gen_ad_topup_btn: '広告を見てチャージ',
    gen_credits_balance: '保有 {credits} クレジット',
    gen_credits_cost_range: '1回8クレジット消費',
    gen_credits_low_cta: 'クレジットが不足？30秒広告で無料クレジットを獲得',
    gen_complete_msg: '{cost} クレジット消費 · 残り {remaining} クレジット',
    gen_adblock_title: '広告ブロッカーが検出されました',
    gen_adblock_desc: '無料クレジットを獲得するには、広告ブロッカー(AdBlock)を一時的にオフにしてください。',
    gen_adblock_dismiss_btn: 'オフにしました！広告を見てクレジット受取',
    gen_sample_label: 'サンプルを試す：',
    gen_sample_us_tiktok: '米国TikTok 100万再生チャレンジ',
    gen_sample_yt_shorts: 'YouTube Shorts 知識起業',
    plan_create: 'バイラル動画制作プランを作る', plan_new_from_structure: 'この構造で新しい動画を作る', plan_view_original: '元動画を見る',
    plan_generate_5: '制作プラン生成 — 8クレジット', plan_cost_5: '1回8クレジット', plan_label: '制作プラン', plan_viral_structure: 'バイラル構造',
    plan_scenes: 'シーン別制作プラン', plan_ai_prompts: 'AI動画プロンプト', plan_voice_captions: '音声・字幕', plan_editing_timeline: '編集タイムライン',
    plan_copy_veo: 'Veoプロンプトをコピー', plan_copy_runway: 'Runwayプロンプトをコピー', plan_copy_kling: 'Klingプロンプトをコピー', plan_copy_generic: '汎用プロンプトをコピー',
    plan_copy_all: '結果をすべてコピー', plan_download_json: 'JSONをダウンロード', plan_original_structure: '元の構造を参考にした新コンテンツ', plan_original_recreation: '元動画を複製しない再創作結果',

    // ─── Remix Panel ───
    remix_title: 'AIリミックス',
    remix_desc: '別の商品/サービス向けに脚本を再生成します。',
    remix_product_placeholder: '新しい商品/サービス名',
    remix_btn: 'リミックス生成',
    remix_loading: '生成中...',

    // ─── Misc ───
    loading: '読み込み中...',
    error: 'エラーが発生しました',
    retry: '再試行',
    close: '閉じる',
    confirm: '確認',
    cancel: 'キャンセル',
  },
};

const LANG_KEY = 'viralLang';

export function getLang(): Lang {
  if (typeof window === 'undefined') return 'en';
  return (localStorage.getItem(LANG_KEY) as Lang) || 'en';
}

export function t(key: string): string {
  const lang = getLang();
  return T[lang]?.[key] ?? T.en[key] ?? key;
}

export default function LanguageSwitcher() {
  const { language: lang, setLanguage } = useLanguage();
  const [isOpen, setIsOpen] = useState(false);

  async function switchLang(code: Lang) {
    setIsOpen(false);
    try {
      await setLanguage(code);
    } catch {
      // 브라우저 언어는 저장하고, 프로필 저장 실패는 다음 설정 저장에서 재시도합니다.
    }
  }

  const current = LANGS.find(l => l.code === lang) ?? LANGS[0];

  return (
    <div className="relative shrink-0">
      <button 
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-2 px-3 sm:px-4 py-2 rounded-xl text-sm font-medium text-white/70 hover:text-white hover:bg-white/8 transition-all border border-white/10 hover:border-white/20 w-[90px] sm:w-[120px] justify-between"
      >
        <div className="flex items-center gap-1.5 sm:gap-2">
          <Globe size={14} className="sm:w-4 sm:h-4" />
          <span className="text-sm sm:text-base">{current.flag}</span>
        </div>
        <svg className={`w-3 h-3 sm:w-4 sm:h-4 transition-transform ${isOpen ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </button>
      {isOpen && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setIsOpen(false)} />
          <div className="absolute right-0 top-full mt-2 w-48 glass-strong rounded-xl overflow-hidden shadow-xl shadow-black/40 fade-in-up z-50">
            {LANGS.map(l => (
              <button
                key={l.code}
                onClick={() => switchLang(l.code)}
                className={`w-full flex items-center gap-3 px-4 py-3 text-sm font-medium transition-all ${l.code === lang ? 'bg-violet-600/40 text-white' : 'text-white/60 hover:text-white hover:bg-white/8'}`}
              >
                <span className="text-xl">{l.flag}</span> 
                <span className="flex-1 text-left">{l.label}</span>
                {l.code === lang && <span className="text-violet-400">✓</span>}
              </button>
            ))}
          </div>
        </>
      )}
    </div>
  );
}
