'use client';

import Footer from '@/app/components/Footer';
import { useLanguage } from '@/app/components/LanguageProvider';
import Navbar from '@/app/components/Navbar';

const EFFECTIVE_DATE = '2026년 9월 22일';
const CONTACT_EMAIL = 'psunghyi@gmail.com';

function LegalShell({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) {
  return <><Navbar /><main className="flex-1 px-4 pb-16 pt-28 sm:px-6"><article className="mx-auto max-w-3xl"><header className="border-b border-white/10 pb-6"><h1 className="text-3xl font-bold tracking-tight text-white">{title}</h1><p className="mt-2 text-sm text-white/45">{subtitle}</p></header><div className="mt-8 space-y-8 text-sm leading-7 text-white/65 [&_h2]:text-base [&_h2]:font-semibold [&_h2]:text-white [&_li]:my-1 [&_strong]:font-semibold [&_strong]:text-white/85">{children}</div></article></main><Footer /></>;
}

function KoreanPolicy() {
  return <LegalShell title="개인정보처리방침" subtitle={`시행일: ${EFFECTIVE_DATE} · ViralScriptAI`}>
    <p>ViralScriptAI(이하 “서비스”)는 계정 운영과 AI 영상 기획 서비스 제공에 필요한 범위에서만 개인정보를 처리합니다. 이 방침은 수집 정보, 이용 목적, 보관 기간 및 이용자의 권리를 설명합니다.</p>
    <section><h2>1. 개인정보처리자 및 문의처</h2><p>개인정보 관련 문의, 열람·정정·삭제·처리정지 요청은 아래로 보내실 수 있습니다.</p><p><strong>서비스명:</strong> ViralScriptAI<br /><strong>문의 이메일:</strong> <a className="text-violet-300 underline underline-offset-4" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a></p></section>
    <section><h2>2. 수집하는 정보</h2><ul className="list-disc pl-5"><li><strong>계정 정보:</strong> 이름, 이메일 주소, 국가번호, 전화번호, 인증 제공자 식별자, 계정 상태 및 설정</li><li><strong>Google 로그인:</strong> Google이 제공하는 이메일 주소와 이름 등 로그인에 필요한 기본 프로필 정보. 전화번호와 추천인 코드는 서비스에서 별도로 입력받습니다.</li><li><strong>서비스 이용 정보:</strong> 입력한 주제·요청·참고 URL, 생성 결과와 이력, 크레딧 잔액·사용 내역, 추천 관계, 설문 응답</li><li><strong>문의·결제 정보:</strong> 문의 및 이의신청 내용, 결제 기능이 활성화된 경우 주문·결제 검증 정보</li><li><strong>자동 생성 정보:</strong> 로그인 세션·보안에 필요한 쿠키, IP 주소, 브라우저·기기 정보, 오류 및 접근 로그</li></ul><p>정보는 회원가입·Google 로그인·서비스 이용·문의·결제 과정에서 수집됩니다. 비밀번호와 카드번호를 서비스가 직접 저장하지 않으며, 영상 원본 파일을 업로드받지 않습니다.</p></section>
    <section><h2>3. 이용 목적</h2><ul className="list-disc pl-5"><li>로그인, 본인 식별, 계정 복구 및 고객 지원</li><li>영상 기획 생성, 생성 이력 제공, 크레딧 차감·지급 및 결제 검증</li><li>부정 이용 방지, 서비스 안정성·보안 유지 및 법적 의무 이행</li><li>서비스 품질 개선을 위한 오류 분석 및 통계</li></ul></section>
    <section><h2>4. 보관 기간 및 파기</h2><p>계정 및 생성 이력은 회원 탈퇴 또는 처리 목적 달성 시 지체 없이 삭제합니다. 다만 탈퇴한 이메일의 재가입 제한 기록은 30일간 보관하며, 결제·분쟁·보안 기록은 관련 법령 또는 분쟁 해결에 필요한 기간 동안 보관할 수 있습니다.</p><p>보관 기간이 끝난 정보는 복구할 수 없는 방법으로 삭제합니다. 전자 파일은 접근을 차단한 뒤 안전하게 삭제하고, 출력물은 분쇄 또는 소각합니다.</p></section>
    <section><h2>5. 처리 위탁 및 국외 이전</h2><p>서비스 운영을 위해 아래 사업자에게 필요한 정보 처리를 맡기거나 전송합니다. 각 사업자는 해당 업무 수행에 필요한 범위에서만 정보를 처리합니다.</p><div className="overflow-x-auto rounded-lg border border-white/10"><table className="min-w-[640px] w-full text-left text-xs leading-6"><thead className="bg-white/[0.04] text-white/75"><tr><th className="px-3 py-2">사업자</th><th className="px-3 py-2">목적·전송 정보</th><th className="px-3 py-2">이전 시점·방법</th><th className="px-3 py-2">보관</th></tr></thead><tbody className="divide-y divide-white/8"><tr><td className="px-3 py-2">Supabase</td><td className="px-3 py-2">인증·데이터베이스: 계정, 서비스 이용 정보</td><td className="px-3 py-2">회원가입·이용 시 암호화 통신으로 전송</td><td className="px-3 py-2">탈퇴 또는 목적 달성 시까지</td></tr><tr><td className="px-3 py-2">Vercel</td><td className="px-3 py-2">웹 호스팅·보안: 접속 및 요청 정보</td><td className="px-3 py-2">접속 시 암호화 통신으로 전송</td><td className="px-3 py-2">서비스 제공에 필요한 기간</td></tr><tr><td className="px-3 py-2">Google Gemini</td><td className="px-3 py-2">AI 생성: 주제, 요청, 참고 URL 및 생성에 필요한 텍스트</td><td className="px-3 py-2">생성 요청 시 암호화 통신으로 전송</td><td className="px-3 py-2">Google 정책에 따른 기간</td></tr><tr><td className="px-3 py-2">Google</td><td className="px-3 py-2">소셜 로그인: 이메일·이름 등 기본 프로필</td><td className="px-3 py-2">Google 로그인 선택 시 OAuth 방식으로 수신</td><td className="px-3 py-2">계정 탈퇴 또는 목적 달성 시까지</td></tr><tr><td className="px-3 py-2">결제 제공자</td><td className="px-3 py-2">결제 활성화 시 주문·결제 검증 정보</td><td className="px-3 py-2">결제 요청 시 암호화 통신으로 전송</td><td className="px-3 py-2">관련 법령 및 제공자 정책에 따른 기간</td></tr></tbody></table></div><p>참고 영상 URL을 분석하는 기능을 사용할 때에는 공개 URL의 메타데이터 처리에 외부 데이터 제공자가 이용될 수 있습니다. 광고는 일반 표시 광고로 제공될 수 있으나, 현재 표시 광고 시청만으로 크레딧이 지급되지는 않습니다.</p></section>
    <section><h2>6. 이용자의 권리</h2><p>이용자는 자신의 개인정보에 대해 열람, 정정·삭제, 처리정지 및 동의 철회를 요청할 수 있습니다. 가능한 정보는 계정 설정에서 직접 수정하거나 탈퇴할 수 있으며, 그 밖의 요청은 위 문의처로 보내 주세요. 법령상 제한이 있는 경우에는 그 사유를 안내합니다.</p></section>
    <section><h2>7. 안전성 확보 조치</h2><p>서비스는 전송 구간 암호화, 접근 권한 관리, 사용자별 데이터 접근 제어, 비밀 키의 서버 환경 분리 및 접근 로그 관리 등 합리적인 보호 조치를 적용합니다. 다만 인터넷 환경의 특성상 절대적인 보안을 보장할 수는 없습니다.</p></section>
    <section><h2>8. 방침 변경</h2><p>방침을 변경하는 경우 시행일과 변경 내용을 이 페이지에 공개합니다. 이용자 권리에 중대한 영향을 주는 변경은 합리적인 기간 전에 별도로 알립니다.</p></section>
  </LegalShell>;
}

function EnglishPolicy() {
  return <LegalShell title="Privacy Policy" subtitle="Effective September 22, 2026 · ViralScriptAI"><p>ViralScriptAI processes only the information needed to operate accounts, provide AI video-planning features, prevent abuse, and support users.</p><section><h2>1. Information we process</h2><p>We process account details (name, email, country calling code, phone number, authentication identifier, account status and settings); Google basic profile information used for sign-in; generation inputs, reference URLs, results and history; credits and promotional activity; support messages; and, when enabled, payment-verification records. Essential session cookies, IP address, browser/device data, error and security logs may also be processed.</p></section><section><h2>2. Why we use it</h2><p>We use this information for authentication, account recovery, service delivery, credit and payment verification, security and abuse prevention, support, legal compliance, and reliability improvements.</p></section><section><h2>3. Providers and international processing</h2><p>Supabase provides authentication and database services; Vercel provides hosting and security infrastructure; Google Gemini processes the text required for generation; Google provides optional social sign-in; and a payment provider processes payments only when that feature is enabled. A public reference URL may be processed by a metadata provider when you request URL analysis. Data is transmitted using encrypted connections when these services are used and retained only as necessary for the service, applicable provider policy, legal obligations, or dispute resolution.</p></section><section><h2>4. Retention and deletion</h2><p>We delete account data and generation history when an account is deleted or the purpose ends, unless retention is required for security, payment, dispute, or legal reasons. A deleted-email restriction record may be retained for 30 days. Electronic records are securely deleted so they cannot be restored.</p></section><section><h2>5. Your choices and contact</h2><p>You may update available profile details or delete your account in Settings. To request access, correction, deletion, or restriction, contact <a className="text-violet-300 underline underline-offset-4" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>. Do not send passwords, payment credentials, or API keys through support.</p></section><section><h2>6. Changes</h2><p>We will post material changes on this page before they take effect. Display advertisements may be shown, but viewing a display advertisement alone does not grant credits. Ad rewards are currently disabled because server-side reward verification is unavailable.</p></section></LegalShell>;
}

export default function PrivacyPage() { const { language } = useLanguage(); return language === 'ko' ? <KoreanPolicy /> : <EnglishPolicy />; }
